-- Univec SDK public client (generated by @voxgig/sdkgen).
--
-- Constructors (newSdk / testSdk) and one op namespace per entity. Entities are
-- generic: every op delegates to the config-driven SdkRuntime, so the pipeline
-- is identical for every entity and every API.

import VoxgigStruct
import SdkRuntime
import SdkConfig

open VoxgigStruct

namespace Sdk

/-- Construct a live client from an options map (empty map = defaults). -/
def newSdk (options : Value) : SIO Value :=
  SdkRuntime.mkClientV options SdkConfig.configJson

/-- No-argument convenience constructor. -/
def newSdk0 : SIO Value := do newSdk (← emptyMap)

/-- Construct a test-mode client: operations are answered from an in-memory
    store seeded with the entity test data, so no server is needed. -/
def testSdk (seed : Value) (options : Value) : SIO Value :=
  SdkRuntime.mkTestClientV options SdkConfig.configJson seed

/-- Test client with default options. -/
def testSdk0 (seed : Value) : SIO Value := do testSdk seed (← emptyMap)

end Sdk

namespace Convert
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "convert" d co
end Convert

namespace Embed
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "embed" d co
end Embed

namespace Ephemeral_key
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "ephemeral_key" d co
end Ephemeral_key

namespace Model
  def list (c m co : Value) : SIO Value := SdkRuntime.opList c "model" m co
end Model

