/* Generated by @voxgig/sdkgen. Do not edit. */
'use strict'

// Seed data for the SDK's offline mock transport, so the entity tests
// exercise real code paths without a server.
const SEED = {
  entity: {
    convert: {
      convert0: {"bridge_model":"bridge_model0","embeddings":[],"source_model":"source_model0","target_model":"target_model0","texts":[]},
      convert1: {"bridge_model":"bridge_model1","embeddings":[],"source_model":"source_model1","target_model":"target_model1","texts":[]},
    },
    embed: {
      embed0: {"embeddings":[],"model":"model0","texts":[]},
      embed1: {"embeddings":[],"model":"model1","texts":[]},
    },
    ephemeral_key: {
      ephemeral_key0: {"dailyLimit":100,"dailyUsed":100,"key":"key0","resetsAt":"resetsAt0"},
      ephemeral_key1: {"dailyLimit":200,"dailyUsed":200,"key":"key1","resetsAt":"resetsAt1"},
    },
    model: {
      model0: {"modelType":"modelType0","name":"name0","targetDim":100,"targetModel":"targetModel0"},
      model1: {"modelType":"modelType1","name":"name1","targetDim":200,"targetModel":"targetModel1"},
    },
  },
}

module.exports = { SEED }
