/* Generated by @voxgig/sdkgen. Do not edit. */
'use strict'

const { describe, it, before } = require('node:test')
const assert = require('node:assert')

const Seneca = require('seneca')

const UnivecProvider = require('../dist/univec-provider')
const UnivecProviderDoc = require('../dist/UnivecProvider-doc')

const SenecaMsgTest = require('seneca-msg-test')
const { Maintain } = require('@seneca/maintain')

const { SEED } = require('./seed')

const BasicMessages = require('../dist-test/basic.messages')


describe('univec-provider', () => {

  it('happy', async () => {
    assert.notEqual(UnivecProvider, undefined)
    assert.notEqual(UnivecProviderDoc, undefined)

    const seneca = await makeSeneca()

    assert.partialDeepStrictEqual(
      await seneca.post('sys:provider,provider:univec,get:info'),
      {
        ok: true,
        name: 'univec',
      },
    )
  })


  it('messages', async () => {
    const seneca = await makeSeneca()
    await SenecaMsgTest(seneca, BasicMessages)()
  })


  it('sdk-export', async () => {
    const seneca = await makeSeneca()
    const sdk = seneca.export('UnivecProvider/sdk')()

    assert.equal(typeof sdk.Convert, 'function')
    assert.equal(typeof sdk.Embed, 'function')
    assert.equal(typeof sdk.EphemeralKey, 'function')
    assert.equal(typeof sdk.Model, 'function')
  })


  it('model-list', async () => {
    const seneca = await makeSeneca()
    const list = await seneca.entity('provider/univec/model').list$()

    assert.equal(list.length, 2)

    // Entities must come back as Seneca entities under this plugin's canon.
    // The SDK tags its own results with its entity marker, which must not
    // survive into the Seneca entity.
    assert.equal(
      list[0].canon$({ string: true }),
      'provider/univec/model',
    )
  })


  it('maintain', async () => {
    const exclude = []

    // check_default proves the default branch is main by looking for
    // [branch "main"] in .git/config. Only a branch checkout records that
    // section: a pull_request build checks out the merge ref, and the
    // publish build checks out a tag as a detached HEAD. Neither says
    // anything about what the default branch is, so skip rather than fail.
    if ('pull_request' === process.env.GITHUB_EVENT_NAME ||
        'tag' === process.env.GITHUB_REF_TYPE) {
      exclude.push('check_default')
    }

    // url_pkgjson locates package.json by comparing process.cwd() + '/package.json'
    // against a path found with Filehound. On Windows those are the same file
    // spelt with different separators, so the url is never read.
    if ('win32' === process.platform) {
      exclude.push('url_pkgjson')
    }

    await Maintain({ exclude })
  })

})


// Default to the SDK's offline mock transport, seeded from ./seed.
async function makeSeneca(pluginopts) {
  pluginopts = pluginopts || { test: true, testopts: SEED }

  const seneca = Seneca({ legacy: false })
    .test()
    .use('promisify')
    .use('entity')
    .use('env', {
      // Declared so the provider convention is exercised, and defaulted so
      // the suite runs with nothing configured.
      var: {
        $UNIVEC_APIKEY: '',
      },
    })
    .use('provider', {
      provider: {
        univec: {
          keys: {
            apikey: { value: '$UNIVEC_APIKEY' },
          },
        },
      },
    })
    .use(UnivecProvider, pluginopts)

  return seneca.ready()
}
