// Generated API configuration (mirrors core/config.go).

#include "api.h"

#include <string.h>

voxgig_value* make_config(void) {
  return cmap(4,
    "main", cmap(4,
      "name", v_str("Univec"),
      "slug", v_str("univec"),
      "version", v_str("0.1.1"),
      "target", v_str("c")),
    "feature", cmap(1,
      "test", cmap(2,
        "options", cmap(1,
          "active", v_bool(false)),
        "transport", v_str("base"))),
    "options", cmap(4,
      "base", v_str("https://api.univec.ai"),
      "headers", cmap(1,
        "content-type", v_str("application/json")),
      "entity", cmap(4,
        "convert", v_map(),
        "embed", v_map(),
        "ephemeral_key", v_map(),
        "model", v_map()),
      "auth", cmap(1,
        "prefix", v_str("Bearer"))),
    "entity", cmap(4,
      "convert", cmap(4,
        "fields", clist(5,
          cmap(4,
            "name", v_str("bridge_model"),
            "req", v_bool(true),
            "short", v_str("Embed model used to vectorise the text before translation."),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("embeddings"),
            "req", v_bool(true),
            "short", v_str("Translated vectors, in the target model's dimension."),
            "type", v_str("`$ARRAY`")),
          cmap(4,
            "name", v_str("source_model"),
            "req", v_bool(true),
            "short", v_str("Model space the supplied vectors are currently in."),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("target_model"),
            "req", v_bool(true),
            "short", v_str("Model space to translate into."),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("texts"),
            "req", v_bool(true),
            "short", v_str("Texts to embed and translate."),
            "type", v_str("`$ARRAY`"))),
        "name", v_str("convert"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(4,
              cmap(7,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/v1/convert"),
                "parts", clist(2,
                  v_str("v1"),
                  v_str("convert")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body.data`"))),
              cmap(7,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/v1/embed-bridge"),
                "parts", clist(2,
                  v_str("v1"),
                  v_str("embed-bridge")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body.data`"))),
              cmap(7,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/v1/ephemeral/convert"),
                "parts", clist(3,
                  v_str("v1"),
                  v_str("ephemeral"),
                  v_str("convert")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body.data`"))),
              cmap(7,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/v1/ephemeral/embed-bridge"),
                "parts", clist(3,
                  v_str("v1"),
                  v_str("ephemeral"),
                  v_str("embed-bridge")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body.data`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "embed", cmap(4,
        "fields", clist(3,
          cmap(4,
            "name", v_str("embeddings"),
            "req", v_bool(true),
            "short", v_str("One vector per input text, in input order."),
            "type", v_str("`$ARRAY`")),
          cmap(4,
            "name", v_str("model"),
            "req", v_bool(true),
            "short", v_str("Model that produced the vectors."),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("texts"),
            "req", v_bool(true),
            "short", v_str("Texts to embed."),
            "type", v_str("`$ARRAY`"))),
        "name", v_str("embed"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(2,
              cmap(7,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/v1/embed"),
                "parts", clist(2,
                  v_str("v1"),
                  v_str("embed")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body.data`"))),
              cmap(7,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/v1/ephemeral/embed"),
                "parts", clist(3,
                  v_str("v1"),
                  v_str("ephemeral"),
                  v_str("embed")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body.data`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "ephemeral_key", cmap(4,
        "fields", clist(4,
          cmap(4,
            "name", v_str("dailyLimit"),
            "req", v_bool(true),
            "short", v_str("Calls permitted per day."),
            "type", v_str("`$INTEGER`")),
          cmap(4,
            "name", v_str("dailyUsed"),
            "req", v_bool(true),
            "short", v_str("Calls already used today."),
            "type", v_str("`$INTEGER`")),
          cmap(4,
            "name", v_str("key"),
            "req", v_bool(true),
            "short", v_str("The ephemeral API key, prefixed `eph_`."),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("resetsAt"),
            "req", v_bool(true),
            "short", v_str("When the daily allowance resets."),
            "type", v_str("`$STRING`"))),
        "name", v_str("ephemeral_key"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(7,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/v1/ephemeral/key"),
                "parts", clist(3,
                  v_str("v1"),
                  v_str("ephemeral"),
                  v_str("key")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body.data`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "model", cmap(4,
        "fields", clist(10,
          cmap(3,
            "name", v_str("eval"),
            "short", v_str("Retrieval-fidelity metrics for a convert model."),
            "type", v_str("`$OBJECT`")),
          cmap(3,
            "name", v_str("executionProvider"),
            "short", v_str("Hardware backend, e.g."),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("modelCard"),
            "short", v_str("Convert models only: training provenance and architecture detail."),
            "type", v_str("`$OBJECT`")),
          cmap(4,
            "name", v_str("modelType"),
            "req", v_bool(true),
            "short", v_str("`embed` for text-to-vector models, `convert` for space-translation models."),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("name"),
            "req", v_bool(true),
            "short", v_str("Model identifier used in requests."),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("sequenceLen"),
            "short", v_str("Embed models only: maximum input sequence length."),
            "type", v_str("`$INTEGER`")),
          cmap(3,
            "name", v_str("sourceDim"),
            "short", v_str("Convert models only: source vector dimension."),
            "type", v_str("`$INTEGER`")),
          cmap(3,
            "name", v_str("sourceModel"),
            "short", v_str("Convert models only: the source model space."),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("targetDim"),
            "req", v_bool(true),
            "short", v_str("Dimension of the produced vectors."),
            "type", v_str("`$INTEGER`")),
          cmap(4,
            "name", v_str("targetModel"),
            "req", v_bool(true),
            "short", v_str("The model space produced."),
            "type", v_str("`$STRING`"))),
        "name", v_str("model"),
        "op", cmap(1,
          "list", cmap(3,
            "input", v_str("data"),
            "name", v_str("list"),
            "points", clist(1,
              cmap(7,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/v1/models"),
                "parts", clist(2,
                  v_str("v1"),
                  v_str("models")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body.data`")))))),
        "relations", cmap(1,
          "ancestors", v_list()))));
}

// SHARED CONFIG (sdkgen rung L2).
//
// The SDK reads the config on every request and never writes to it, so one
// instance is shared by every client rather than rebuilt per client. Above the
// size threshold make_config re-parses the whole embedded JSON, so this is the
// difference between parsing the model once and once per client.
//
// Deliberately never freed: it lives for the life of the process, like any
// other program-lifetime singleton.
static voxgig_value* shared_config_val = NULL;

// The process-wide config, built once on first use.
//
// The returned value is SHARED: treat it as read-only. Callers that need to
// mutate should use make_config, which always returns a fresh copy.
voxgig_value* shared_config(void) {
  if (NULL == shared_config_val) {
    shared_config_val = make_config();
  }
  return shared_config_val;
}

Feature* feature_test_new(void);

Feature* make_feature(const char* name) {
  if (strcmp(name, "test") == 0) return feature_test_new();
  return feature_base_new();
}
