// Generated API configuration (mirrors core/config.go).

#include "api.h"

#include <string.h>

voxgig_value* make_config(void) {
  return cmap(4,
    "main", cmap(4,
      "name", v_str("Univec"),
      "slug", v_str("univec"),
      "version", v_str("0.1.2"),
      "target", v_str("c")),
    "feature", cmap(19,
      "audit", cmap(4,
        "options", cmap(3,
          "active", v_bool(false),
          "actor", v_str("anonymous"),
          "max", v_num(1000)),
        "optspec", v_map(),
        "strict", v_bool(false),
        "transport", v_str("none")),
      "cache", cmap(4,
        "options", cmap(4,
          "active", v_bool(false),
          "max", v_num(256),
          "methods", clist(1,
            v_str("GET")),
          "ttl", v_num(5000)),
        "optspec", v_map(),
        "strict", v_bool(false),
        "transport", v_str("wrap")),
      "clienttrack", cmap(4,
        "options", cmap(2,
          "active", v_bool(false),
          "clientVersion", v_str("0.0.1")),
        "optspec", v_map(),
        "strict", v_bool(false),
        "transport", v_str("none")),
      "cost", cmap(4,
        "options", cmap(9,
          "active", v_bool(false),
          "budget", v_num(0),
          "currency", v_str("USD"),
          "header", v_str(""),
          "onBudget", v_str("warn"),
          "path", v_str(""),
          "perUnit", v_num(0),
          "rates", v_map(),
          "unit", v_num(0)),
        "optspec", v_map(),
        "strict", v_bool(false),
        "transport", v_str("wrap")),
      "debug", cmap(4,
        "options", cmap(3,
          "active", v_bool(false),
          "max", v_num(100),
          "redact", clist(7,
            v_str("authorization"),
            v_str("cookie"),
            v_str("set-cookie"),
            v_str("api-key"),
            v_str("apikey"),
            v_str("x-api-key"),
            v_str("idempotency-key"))),
        "optspec", v_map(),
        "strict", v_bool(false),
        "transport", v_str("none")),
      "idempotency", cmap(4,
        "options", cmap(4,
          "active", v_bool(false),
          "header", v_str("Idempotency-Key"),
          "methods", clist(4,
            v_str("POST"),
            v_str("PUT"),
            v_str("PATCH"),
            v_str("DELETE")),
          "ops", clist(3,
            v_str("create"),
            v_str("update"),
            v_str("remove"))),
        "optspec", v_map(),
        "strict", v_bool(false),
        "transport", v_str("none")),
      "log", cmap(4,
        "options", cmap(1,
          "active", v_bool(true)),
        "optspec", v_map(),
        "strict", v_bool(false),
        "transport", v_str("none")),
      "metrics", cmap(4,
        "options", cmap(1,
          "active", v_bool(false)),
        "optspec", v_map(),
        "strict", v_bool(false),
        "transport", v_str("none")),
      "netsim", cmap(4,
        "options", cmap(11,
          "active", v_bool(false),
          "errorTimes", v_num(0),
          "failEvery", v_num(0),
          "failRate", v_num(0),
          "failStatus", v_num(503),
          "failTimes", v_num(0),
          "latency", v_num(0),
          "offline", v_bool(false),
          "rateLimitTimes", v_num(0),
          "retryAfter", v_num(0),
          "seed", v_num(1)),
        "optspec", v_map(),
        "strict", v_bool(false),
        "transport", v_str("wrap")),
      "paging", cmap(4,
        "options", cmap(7,
          "active", v_bool(false),
          "afterVar", v_str("after"),
          "cursorParam", v_str("cursor"),
          "firstVar", v_str("first"),
          "limitParam", v_str("limit"),
          "pageParam", v_str("page"),
          "startPage", v_num(1)),
        "optspec", v_map(),
        "strict", v_bool(false),
        "transport", v_str("none")),
      "proxy", cmap(4,
        "options", cmap(4,
          "active", v_bool(false),
          "fromEnv", v_bool(false),
          "noProxy", v_list(),
          "url", v_str("")),
        "optspec", v_map(),
        "strict", v_bool(false),
        "transport", v_str("wrap")),
      "ratelimit", cmap(4,
        "options", cmap(3,
          "active", v_bool(false),
          "burst", v_num(5),
          "rate", v_num(5)),
        "optspec", v_map(),
        "strict", v_bool(false),
        "transport", v_str("wrap")),
      "rbac", cmap(4,
        "options", cmap(4,
          "active", v_bool(false),
          "deny", v_bool(false),
          "permissions", v_list(),
          "rules", v_map()),
        "optspec", v_map(),
        "strict", v_bool(false),
        "transport", v_str("none")),
      "retry", cmap(4,
        "options", cmap(6,
          "active", v_bool(false),
          "factor", v_num(2),
          "maxDelay", v_num(2000),
          "minDelay", v_num(50),
          "retries", v_num(2),
          "statuses", clist(7,
            v_num(408),
            v_num(425),
            v_num(429),
            v_num(500),
            v_num(502),
            v_num(503),
            v_num(504))),
        "optspec", v_map(),
        "strict", v_bool(false),
        "transport", v_str("wrap")),
      "secrets", cmap(4,
        "options", cmap(5,
          "active", v_bool(false),
          "cache", v_bool(true),
          "exchange", cmap(8,
            "active", v_bool(false),
            "method", v_str("POST"),
            "path", v_str("auth/token"),
            "refresh", v_str(""),
            "request", v_str("refresh_token"),
            "response", v_str("access_token"),
            "retries", v_num(1),
            "statuses", clist(1,
              v_num(401))),
          "name", v_str("univec"),
          "providers", clist(1,
            cmap(2,
              "kind", v_str("boru"),
              "namespace", v_str("sdk")))),
        "optspec", v_map(),
        "strict", v_bool(false),
        "transport", v_str("wrap")),
      "streaming", cmap(4,
        "options", cmap(3,
          "active", v_bool(false),
          "chunkDelay", v_num(0),
          "chunkSize", v_num(0)),
        "optspec", v_map(),
        "strict", v_bool(false),
        "transport", v_str("none")),
      "telemetry", cmap(4,
        "options", cmap(1,
          "active", v_bool(false)),
        "optspec", v_map(),
        "strict", v_bool(false),
        "transport", v_str("none")),
      "test", cmap(4,
        "options", cmap(1,
          "active", v_bool(false)),
        "optspec", v_map(),
        "strict", v_bool(false),
        "transport", v_str("base")),
      "timeout", cmap(4,
        "options", cmap(2,
          "active", v_bool(false),
          "ms", v_num(30000)),
        "optspec", v_map(),
        "strict", v_bool(false),
        "transport", v_str("wrap"))),
    "options", cmap(4,
      "base", v_str("https://api.univec.ai"),
      "headers", cmap(1,
        "content-type", v_str("application/json")),
      "entity", cmap(4,
        "convert", v_map(),
        "embed", v_map(),
        "ephemeral_key", v_map(),
        "model", v_map()),
      "auth", cmap(1,
        "prefix", v_str("Bearer"))),
    "entity", cmap(4,
      "convert", cmap(4,
        "fields", clist(5,
          cmap(4,
            "name", v_str("bridge_model"),
            "req", v_bool(true),
            "short", v_str("Embed model used to vectorise the text before translation."),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("embeddings"),
            "req", v_bool(true),
            "short", v_str("Translated vectors, in the target model's dimension."),
            "type", v_str("`$ARRAY`")),
          cmap(4,
            "name", v_str("source_model"),
            "req", v_bool(true),
            "short", v_str("Model space the supplied vectors are currently in."),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("target_model"),
            "req", v_bool(true),
            "short", v_str("Model space to translate into."),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("texts"),
            "req", v_bool(true),
            "short", v_str("Texts to embed and translate."),
            "type", v_str("`$ARRAY`"))),
        "name", v_str("convert"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(4,
              cmap(8,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/v1/convert"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("v1")),
                  cmap(1,
                    "lit", v_str("convert"))),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body.data`")),
                "parts", clist(2,
                  v_str("v1"),
                  v_str("convert"))),
              cmap(8,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/v1/embed-bridge"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("v1")),
                  cmap(1,
                    "lit", v_str("embed-bridge"))),
                "select", cmap(1,
                  "$action", v_str("bridge")),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body.data`")),
                "parts", clist(2,
                  v_str("v1"),
                  v_str("embed-bridge"))),
              cmap(8,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/v1/ephemeral/convert"),
                "segments", clist(3,
                  cmap(1,
                    "lit", v_str("v1")),
                  cmap(1,
                    "lit", v_str("ephemeral")),
                  cmap(1,
                    "lit", v_str("convert"))),
                "select", cmap(1,
                  "$action", v_str("ephemeral")),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body.data`")),
                "parts", clist(3,
                  v_str("v1"),
                  v_str("ephemeral"),
                  v_str("convert"))),
              cmap(8,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/v1/ephemeral/embed-bridge"),
                "segments", clist(3,
                  cmap(1,
                    "lit", v_str("v1")),
                  cmap(1,
                    "lit", v_str("ephemeral")),
                  cmap(1,
                    "lit", v_str("embed-bridge"))),
                "select", cmap(1,
                  "$action", v_str("ephemeral_bridge")),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body.data`")),
                "parts", clist(3,
                  v_str("v1"),
                  v_str("ephemeral"),
                  v_str("embed-bridge")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "embed", cmap(4,
        "fields", clist(3,
          cmap(4,
            "name", v_str("embeddings"),
            "req", v_bool(true),
            "short", v_str("One vector per input text, in input order."),
            "type", v_str("`$ARRAY`")),
          cmap(4,
            "name", v_str("model"),
            "req", v_bool(true),
            "short", v_str("Model that produced the vectors."),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("texts"),
            "req", v_bool(true),
            "short", v_str("Texts to embed."),
            "type", v_str("`$ARRAY`"))),
        "name", v_str("embed"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(2,
              cmap(8,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/v1/embed"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("v1")),
                  cmap(1,
                    "lit", v_str("embed"))),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body.data`")),
                "parts", clist(2,
                  v_str("v1"),
                  v_str("embed"))),
              cmap(8,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/v1/ephemeral/embed"),
                "segments", clist(3,
                  cmap(1,
                    "lit", v_str("v1")),
                  cmap(1,
                    "lit", v_str("ephemeral")),
                  cmap(1,
                    "lit", v_str("embed"))),
                "select", cmap(1,
                  "$action", v_str("ephemeral")),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body.data`")),
                "parts", clist(3,
                  v_str("v1"),
                  v_str("ephemeral"),
                  v_str("embed")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "ephemeral_key", cmap(4,
        "fields", clist(4,
          cmap(4,
            "name", v_str("dailyLimit"),
            "req", v_bool(true),
            "short", v_str("Calls permitted per day."),
            "type", v_str("`$INTEGER`")),
          cmap(4,
            "name", v_str("dailyUsed"),
            "req", v_bool(true),
            "short", v_str("Calls already used today."),
            "type", v_str("`$INTEGER`")),
          cmap(4,
            "name", v_str("key"),
            "req", v_bool(true),
            "short", v_str("The ephemeral API key, prefixed `eph_`."),
            "type", v_str("`$STRING`")),
          cmap(5,
            "format", v_str("date-time"),
            "name", v_str("resetsAt"),
            "req", v_bool(true),
            "short", v_str("When the daily allowance resets."),
            "type", v_str("`$STRING`"))),
        "name", v_str("ephemeral_key"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(8,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/v1/ephemeral/key"),
                "segments", clist(3,
                  cmap(1,
                    "lit", v_str("v1")),
                  cmap(1,
                    "lit", v_str("ephemeral")),
                  cmap(1,
                    "lit", v_str("key"))),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body.data`")),
                "parts", clist(3,
                  v_str("v1"),
                  v_str("ephemeral"),
                  v_str("key")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "model", cmap(4,
        "fields", clist(10,
          cmap(3,
            "name", v_str("eval"),
            "short", v_str("Retrieval-fidelity metrics for a convert model."),
            "type", v_str("`$OBJECT`")),
          cmap(3,
            "name", v_str("executionProvider"),
            "short", v_str("Hardware backend, e.g."),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("modelCard"),
            "short", v_str("Convert models only: training provenance and architecture detail."),
            "type", v_str("`$OBJECT`")),
          cmap(4,
            "name", v_str("modelType"),
            "req", v_bool(true),
            "short", v_str("`embed` for text-to-vector models, `convert` for space-translation models."),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("name"),
            "req", v_bool(true),
            "short", v_str("Model identifier used in requests."),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("sequenceLen"),
            "short", v_str("Embed models only: maximum input sequence length."),
            "type", v_str("`$INTEGER`")),
          cmap(3,
            "name", v_str("sourceDim"),
            "short", v_str("Convert models only: source vector dimension."),
            "type", v_str("`$INTEGER`")),
          cmap(3,
            "name", v_str("sourceModel"),
            "short", v_str("Convert models only: the source model space."),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("targetDim"),
            "req", v_bool(true),
            "short", v_str("Dimension of the produced vectors."),
            "type", v_str("`$INTEGER`")),
          cmap(4,
            "name", v_str("targetModel"),
            "req", v_bool(true),
            "short", v_str("The model space produced."),
            "type", v_str("`$STRING`"))),
        "name", v_str("model"),
        "op", cmap(1,
          "list", cmap(3,
            "input", v_str("data"),
            "name", v_str("list"),
            "points", clist(1,
              cmap(8,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/v1/models"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("v1")),
                  cmap(1,
                    "lit", v_str("models"))),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body.data`")),
                "parts", clist(2,
                  v_str("v1"),
                  v_str("models")))))),
        "relations", cmap(1,
          "ancestors", v_list()))));
}

// SHARED CONFIG (sdkgen rung L2).
//
// The SDK reads the config on every request and never writes to it, so one
// instance is shared by every client rather than rebuilt per client. Above the
// size threshold make_config re-parses the whole embedded JSON, so this is the
// difference between parsing the model once and once per client.
//
// Deliberately never freed: it lives for the life of the process, like any
// other program-lifetime singleton.
static voxgig_value* shared_config_val = NULL;

// The process-wide config, built once on first use.
//
// The returned value is SHARED: treat it as read-only. Callers that need to
// mutate should use make_config, which always returns a fresh copy.
voxgig_value* shared_config(void) {
  if (NULL == shared_config_val) {
    shared_config_val = make_config();
  }
  return shared_config_val;
}

Feature* feature_audit_new(void);
Feature* feature_cache_new(void);
Feature* feature_clienttrack_new(void);
Feature* feature_cost_new(void);
Feature* feature_debug_new(void);
Feature* feature_idempotency_new(void);
Feature* feature_log_new(void);
Feature* feature_metrics_new(void);
Feature* feature_netsim_new(void);
Feature* feature_paging_new(void);
Feature* feature_proxy_new(void);
Feature* feature_ratelimit_new(void);
Feature* feature_rbac_new(void);
Feature* feature_retry_new(void);
Feature* feature_secrets_new(void);
Feature* feature_streaming_new(void);
Feature* feature_telemetry_new(void);
Feature* feature_test_new(void);
Feature* feature_timeout_new(void);

Feature* make_feature(const char* name) {
  if (strcmp(name, "audit") == 0) return feature_audit_new();
  if (strcmp(name, "cache") == 0) return feature_cache_new();
  if (strcmp(name, "clienttrack") == 0) return feature_clienttrack_new();
  if (strcmp(name, "cost") == 0) return feature_cost_new();
  if (strcmp(name, "debug") == 0) return feature_debug_new();
  if (strcmp(name, "idempotency") == 0) return feature_idempotency_new();
  if (strcmp(name, "log") == 0) return feature_log_new();
  if (strcmp(name, "metrics") == 0) return feature_metrics_new();
  if (strcmp(name, "netsim") == 0) return feature_netsim_new();
  if (strcmp(name, "paging") == 0) return feature_paging_new();
  if (strcmp(name, "proxy") == 0) return feature_proxy_new();
  if (strcmp(name, "ratelimit") == 0) return feature_ratelimit_new();
  if (strcmp(name, "rbac") == 0) return feature_rbac_new();
  if (strcmp(name, "retry") == 0) return feature_retry_new();
  if (strcmp(name, "secrets") == 0) return feature_secrets_new();
  if (strcmp(name, "streaming") == 0) return feature_streaming_new();
  if (strcmp(name, "telemetry") == 0) return feature_telemetry_new();
  if (strcmp(name, "test") == 0) return feature_test_new();
  if (strcmp(name, "timeout") == 0) return feature_timeout_new();
  return feature_base_new();
}

void** secrets_plugins(size_t* n);

void** feature_plugins(const char* name, size_t* n) {
  if (strcmp(name, "secrets") == 0) return secrets_plugins(n);
  (void)name;
  *n = 0;
  return NULL;
}
