package voxgig.univecsdk.core

import voxgig.univecsdk.utility.Json
import voxgig.univecsdk.feature.secrets.sekreto.plugins.boru
import voxgig.univecsdk.feature.secrets.sekreto.plugins.hashicorp

/** Static SDK configuration and by-name feature construction. */
@Suppress("UNCHECKED_CAST")
object Config {

  fun makeConfig(): MutableMap<String, Any?> {
    return Json.parse(configJson()) as MutableMap<String, Any?>
  }

  // SHARED CONFIG (sdkgen rung L2).
  //
  // The SDK reads the config on every request and never writes to it, so one
  // instance is shared by every client rather than rebuilt per client - the
  // difference between parsing the embedded JSON once and once per client.
  //
  // 'by lazy' defaults to LazyThreadSafetyMode.SYNCHRONIZED, so concurrent
  // first calls build it exactly once.
  //
  // The returned map is SHARED: treat it as read-only. Callers that need to
  // mutate should use makeConfig, which always parses a fresh copy.
  private val sharedConfigVal: MutableMap<String, Any?> by lazy { makeConfig() }

  fun sharedConfig(): MutableMap<String, Any?> = sharedConfigVal

  fun makeFeature(name: String): Feature {
    return when (name) {
      "audit" -> voxgig.univecsdk.feature.AuditFeature()
      "cache" -> voxgig.univecsdk.feature.CacheFeature()
      "clienttrack" -> voxgig.univecsdk.feature.ClienttrackFeature()
      "cost" -> voxgig.univecsdk.feature.CostFeature()
      "debug" -> voxgig.univecsdk.feature.DebugFeature()
      "idempotency" -> voxgig.univecsdk.feature.IdempotencyFeature()
      "log" -> voxgig.univecsdk.feature.LogFeature()
      "metrics" -> voxgig.univecsdk.feature.MetricsFeature()
      "netsim" -> voxgig.univecsdk.feature.NetsimFeature()
      "paging" -> voxgig.univecsdk.feature.PagingFeature()
      "proxy" -> voxgig.univecsdk.feature.ProxyFeature()
      "ratelimit" -> voxgig.univecsdk.feature.RatelimitFeature()
      "rbac" -> voxgig.univecsdk.feature.RbacFeature()
      "retry" -> voxgig.univecsdk.feature.RetryFeature()
      "secrets" -> voxgig.univecsdk.feature.SecretsFeature()
      "streaming" -> voxgig.univecsdk.feature.StreamingFeature()
      "telemetry" -> voxgig.univecsdk.feature.TelemetryFeature()
      "test" -> voxgig.univecsdk.feature.TestFeature()
      "timeout" -> voxgig.univecsdk.feature.TimeoutFeature()
      else -> voxgig.univecsdk.feature.BaseFeature()
    }
  }

  // The plugin definitions the model selected per feature, as List<Any?>
  // so core need not name a feature's types. Empty when no active feature
  // declares active plugin groups for this target - and then no plugin
  // import is emitted either.
  private val featurePluginsMap: Map<String, List<Any?>> = mapOf(
    "secrets" to listOf(boru, hashicorp),
  )

  // featurePlugins is the definitions list for one feature's chain.
  fun featurePlugins(name: String): List<Any?> = featurePluginsMap[name] ?: emptyList()

  private fun configJson(): String {
    val b = StringBuilder()
    b.append("{")
    b.append(" \"main\": {")
    b.append("  \"name\": \"Univec\",")
    b.append("  \"slug\": \"univec\",")
    b.append("  \"version\": \"0.1.2\",")
    b.append("  \"target\": \"kotlin\"")
    b.append(" },")
    b.append(" \"feature\": {")
    b.append("  \"audit\": {")
    b.append("   \"options\": {")
    b.append("    \"active\": false,")
    b.append("    \"actor\": \"anonymous\",")
    b.append("    \"max\": 1000")
    b.append("   },")
    b.append("   \"optspec\": {")
    b.append("    \"now\": \"`\$FUNCTION`\",")
    b.append("    \"sink\": \"`\$FUNCTION`\"")
    b.append("   },")
    b.append("   \"strict\": false,")
    b.append("   \"transport\": \"none\"")
    b.append("  },")
    b.append("  \"cache\": {")
    b.append("   \"options\": {")
    b.append("    \"active\": false,")
    b.append("    \"max\": 256,")
    b.append("    \"methods\": [")
    b.append("     \"GET\"")
    b.append("    ],")
    b.append("    \"ttl\": 5000")
    b.append("   },")
    b.append("   \"optspec\": {")
    b.append("    \"now\": \"`\$FUNCTION`\"")
    b.append("   },")
    b.append("   \"strict\": false,")
    b.append("   \"transport\": \"wrap\"")
    b.append("  },")
    b.append("  \"clienttrack\": {")
    b.append("   \"options\": {")
    b.append("    \"active\": false,")
    b.append("    \"clientVersion\": \"0.0.1\"")
    b.append("   },")
    b.append("   \"optspec\": {")
    b.append("    \"clientName\": \"`\$STRING`\",")
    b.append("    \"clientVersion\": \"`\$STRING`\",")
    b.append("    \"headers\": \"`\$MAP`\",")
    b.append("    \"idgen\": \"`\$FUNCTION`\",")
    b.append("    \"sessionId\": \"`\$STRING`\"")
    b.append("   },")
    b.append("   \"strict\": false,")
    b.append("   \"transport\": \"none\"")
    b.append("  },")
    b.append("  \"cost\": {")
    b.append("   \"options\": {")
    b.append("    \"active\": false,")
    b.append("    \"budget\": 0,")
    b.append("    \"currency\": \"USD\",")
    b.append("    \"header\": \"\",")
    b.append("    \"onBudget\": \"warn\",")
    b.append("    \"path\": \"\",")
    b.append("    \"perUnit\": 0,")
    b.append("    \"rates\": {},")
    b.append("    \"unit\": 0")
    b.append("   },")
    b.append("   \"optspec\": {")
    b.append("    \"actor\": \"`\$STRING`\",")
    b.append("    \"sink\": \"`\$FUNCTION`\"")
    b.append("   },")
    b.append("   \"strict\": false,")
    b.append("   \"transport\": \"wrap\"")
    b.append("  },")
    b.append("  \"debug\": {")
    b.append("   \"options\": {")
    b.append("    \"active\": false,")
    b.append("    \"max\": 100,")
    b.append("    \"redact\": [")
    b.append("     \"authorization\",")
    b.append("     \"cookie\",")
    b.append("     \"set-cookie\",")
    b.append("     \"api-key\",")
    b.append("     \"apikey\",")
    b.append("     \"x-api-key\",")
    b.append("     \"idempotency-key\"")
    b.append("    ]")
    b.append("   },")
    b.append("   \"optspec\": {")
    b.append("    \"now\": \"`\$FUNCTION`\",")
    b.append("    \"onEntry\": \"`\$FUNCTION`\"")
    b.append("   },")
    b.append("   \"strict\": false,")
    b.append("   \"transport\": \"none\"")
    b.append("  },")
    b.append("  \"idempotency\": {")
    b.append("   \"options\": {")
    b.append("    \"active\": false,")
    b.append("    \"header\": \"Idempotency-Key\",")
    b.append("    \"methods\": [")
    b.append("     \"POST\",")
    b.append("     \"PUT\",")
    b.append("     \"PATCH\",")
    b.append("     \"DELETE\"")
    b.append("    ],")
    b.append("    \"ops\": [")
    b.append("     \"create\",")
    b.append("     \"update\",")
    b.append("     \"remove\"")
    b.append("    ]")
    b.append("   },")
    b.append("   \"optspec\": {")
    b.append("    \"keygen\": \"`\$FUNCTION`\"")
    b.append("   },")
    b.append("   \"strict\": false,")
    b.append("   \"transport\": \"none\"")
    b.append("  },")
    b.append("  \"log\": {")
    b.append("   \"options\": {")
    b.append("    \"active\": true")
    b.append("   },")
    b.append("   \"optspec\": {")
    b.append("    \"level\": \"`\$STRING`\",")
    b.append("    \"logger\": \"`\$ANY`\"")
    b.append("   },")
    b.append("   \"strict\": false,")
    b.append("   \"transport\": \"none\"")
    b.append("  },")
    b.append("  \"metrics\": {")
    b.append("   \"options\": {")
    b.append("    \"active\": false")
    b.append("   },")
    b.append("   \"optspec\": {")
    b.append("    \"now\": \"`\$FUNCTION`\"")
    b.append("   },")
    b.append("   \"strict\": false,")
    b.append("   \"transport\": \"none\"")
    b.append("  },")
    b.append("  \"netsim\": {")
    b.append("   \"options\": {")
    b.append("    \"active\": false,")
    b.append("    \"errorTimes\": 0,")
    b.append("    \"failEvery\": 0,")
    b.append("    \"failRate\": 0,")
    b.append("    \"failStatus\": 503,")
    b.append("    \"failTimes\": 0,")
    b.append("    \"latency\": 0,")
    b.append("    \"offline\": false,")
    b.append("    \"rateLimitTimes\": 0,")
    b.append("    \"retryAfter\": 0,")
    b.append("    \"seed\": 1")
    b.append("   },")
    b.append("   \"optspec\": {")
    b.append("    \"latency\": [")
    b.append("     \"`\$ONE`\",")
    b.append("     \"`\$NUMBER`\",")
    b.append("     \"`\$MAP`\"")
    b.append("    ],")
    b.append("    \"sleep\": \"`\$FUNCTION`\"")
    b.append("   },")
    b.append("   \"strict\": false,")
    b.append("   \"transport\": \"wrap\"")
    b.append("  },")
    b.append("  \"paging\": {")
    b.append("   \"options\": {")
    b.append("    \"active\": false,")
    b.append("    \"afterVar\": \"after\",")
    b.append("    \"cursorParam\": \"cursor\",")
    b.append("    \"firstVar\": \"first\",")
    b.append("    \"limitParam\": \"limit\",")
    b.append("    \"pageParam\": \"page\",")
    b.append("    \"startPage\": 1")
    b.append("   },")
    b.append("   \"optspec\": {")
    b.append("    \"limit\": \"`\$NUMBER`\",")
    b.append("    \"ops\": \"`\$LIST`\"")
    b.append("   },")
    b.append("   \"strict\": false,")
    b.append("   \"transport\": \"none\"")
    b.append("  },")
    b.append("  \"proxy\": {")
    b.append("   \"options\": {")
    b.append("    \"active\": false,")
    b.append("    \"fromEnv\": false,")
    b.append("    \"noProxy\": [],")
    b.append("    \"url\": \"\"")
    b.append("   },")
    b.append("   \"optspec\": {")
    b.append("    \"agent\": \"`\$FUNCTION`\"")
    b.append("   },")
    b.append("   \"strict\": false,")
    b.append("   \"transport\": \"wrap\"")
    b.append("  },")
    b.append("  \"ratelimit\": {")
    b.append("   \"options\": {")
    b.append("    \"active\": false,")
    b.append("    \"burst\": 5,")
    b.append("    \"rate\": 5")
    b.append("   },")
    b.append("   \"optspec\": {")
    b.append("    \"now\": \"`\$FUNCTION`\",")
    b.append("    \"sleep\": \"`\$FUNCTION`\"")
    b.append("   },")
    b.append("   \"strict\": false,")
    b.append("   \"transport\": \"wrap\"")
    b.append("  },")
    b.append("  \"rbac\": {")
    b.append("   \"options\": {")
    b.append("    \"active\": false,")
    b.append("    \"deny\": false,")
    b.append("    \"permissions\": [],")
    b.append("    \"rules\": {}")
    b.append("   },")
    b.append("   \"optspec\": {},")
    b.append("   \"strict\": false,")
    b.append("   \"transport\": \"none\"")
    b.append("  },")
    b.append("  \"retry\": {")
    b.append("   \"options\": {")
    b.append("    \"active\": false,")
    b.append("    \"factor\": 2,")
    b.append("    \"maxDelay\": 2000,")
    b.append("    \"minDelay\": 50,")
    b.append("    \"retries\": 2,")
    b.append("    \"statuses\": [")
    b.append("     408,")
    b.append("     425,")
    b.append("     429,")
    b.append("     500,")
    b.append("     502,")
    b.append("     503,")
    b.append("     504")
    b.append("    ]")
    b.append("   },")
    b.append("   \"optspec\": {")
    b.append("    \"jitter\": \"`\$BOOLEAN`\",")
    b.append("    \"sleep\": \"`\$FUNCTION`\"")
    b.append("   },")
    b.append("   \"strict\": false,")
    b.append("   \"transport\": \"wrap\"")
    b.append("  },")
    b.append("  \"secrets\": {")
    b.append("   \"options\": {")
    b.append("    \"active\": false,")
    b.append("    \"cache\": true,")
    b.append("    \"exchange\": {")
    b.append("     \"active\": false,")
    b.append("     \"method\": \"POST\",")
    b.append("     \"path\": \"auth/token\",")
    b.append("     \"refresh\": \"\",")
    b.append("     \"request\": \"refresh_token\",")
    b.append("     \"response\": \"access_token\",")
    b.append("     \"retries\": 1,")
    b.append("     \"statuses\": [")
    b.append("      401")
    b.append("     ]")
    b.append("    },")
    b.append("    \"name\": \"univec\",")
    b.append("    \"providers\": [")
    b.append("     {")
    b.append("      \"kind\": \"boru\",")
    b.append("      \"namespace\": \"sdk\"")
    b.append("     }")
    b.append("    ]")
    b.append("   },")
    b.append("   \"optspec\": {},")
    b.append("   \"strict\": false,")
    b.append("   \"transport\": \"wrap\"")
    b.append("  },")
    b.append("  \"streaming\": {")
    b.append("   \"options\": {")
    b.append("    \"active\": false,")
    b.append("    \"chunkDelay\": 0,")
    b.append("    \"chunkSize\": 0")
    b.append("   },")
    b.append("   \"optspec\": {")
    b.append("    \"ops\": \"`\$LIST`\",")
    b.append("    \"sleep\": \"`\$FUNCTION`\"")
    b.append("   },")
    b.append("   \"strict\": false,")
    b.append("   \"transport\": \"none\"")
    b.append("  },")
    b.append("  \"telemetry\": {")
    b.append("   \"options\": {")
    b.append("    \"active\": false")
    b.append("   },")
    b.append("   \"optspec\": {")
    b.append("    \"exporter\": \"`\$FUNCTION`\",")
    b.append("    \"headers\": \"`\$MAP`\",")
    b.append("    \"idgen\": \"`\$FUNCTION`\",")
    b.append("    \"now\": \"`\$FUNCTION`\"")
    b.append("   },")
    b.append("   \"strict\": false,")
    b.append("   \"transport\": \"none\"")
    b.append("  },")
    b.append("  \"test\": {")
    b.append("   \"options\": {")
    b.append("    \"active\": false")
    b.append("   },")
    b.append("   \"optspec\": {")
    b.append("    \"entity\": \"`\$MAP`\",")
    b.append("    \"net\": \"`\$MAP`\"")
    b.append("   },")
    b.append("   \"strict\": false,")
    b.append("   \"transport\": \"base\"")
    b.append("  },")
    b.append("  \"timeout\": {")
    b.append("   \"options\": {")
    b.append("    \"active\": false,")
    b.append("    \"ms\": 30000")
    b.append("   },")
    b.append("   \"optspec\": {")
    b.append("    \"clearTimer\": \"`\$FUNCTION`\",")
    b.append("    \"setTimer\": \"`\$FUNCTION`\"")
    b.append("   },")
    b.append("   \"strict\": false,")
    b.append("   \"transport\": \"wrap\"")
    b.append("  }")
    b.append(" },")
    b.append(" \"options\": {")
    b.append("  \"base\": \"https://api.univec.ai\",")
    b.append("  \"auth\": {")
    b.append("   \"prefix\": \"Bearer\"")
    b.append("  },")
    b.append("  \"headers\": {")
    b.append("   \"content-type\": \"application/json\"")
    b.append("  },")
    b.append("  \"entity\": {")
    b.append("   \"convert\": {},")
    b.append("   \"embed\": {},")
    b.append("   \"ephemeral_key\": {},")
    b.append("   \"model\": {}")
    b.append("  }")
    b.append(" },")
    b.append(" \"entity\": {")
    b.append("  \"convert\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"name\": \"embeddings\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"Translated vectors, in the target model's dimension.\",")
    b.append("     \"type\": \"`\$ARRAY`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"source_model\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"Model space the supplied vectors are currently in.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"target_model\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"Model space to translate into.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"convert\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"args\": {},")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/v1/convert\",")
    b.append("       \"segments\": [")
    b.append("        {")
    b.append("         \"lit\": \"v1\"")
    b.append("        },")
    b.append("        {")
    b.append("         \"lit\": \"convert\"")
    b.append("        }")
    b.append("       ],")
    b.append("       \"select\": {},")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body.data`\"")
    b.append("       },")
    b.append("       \"parts\": [")
    b.append("        \"v1\",")
    b.append("        \"convert\"")
    b.append("       ]")
    b.append("      },")
    b.append("      {")
    b.append("       \"args\": {},")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/v1/embed-bridge\",")
    b.append("       \"segments\": [")
    b.append("        {")
    b.append("         \"lit\": \"v1\"")
    b.append("        },")
    b.append("        {")
    b.append("         \"lit\": \"embed-bridge\"")
    b.append("        }")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"\$action\": \"bridge\"")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body.data`\"")
    b.append("       },")
    b.append("       \"parts\": [")
    b.append("        \"v1\",")
    b.append("        \"embed-bridge\"")
    b.append("       ]")
    b.append("      },")
    b.append("      {")
    b.append("       \"args\": {},")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/v1/ephemeral/convert\",")
    b.append("       \"segments\": [")
    b.append("        {")
    b.append("         \"lit\": \"v1\"")
    b.append("        },")
    b.append("        {")
    b.append("         \"lit\": \"ephemeral\"")
    b.append("        },")
    b.append("        {")
    b.append("         \"lit\": \"convert\"")
    b.append("        }")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"\$action\": \"ephemeral\"")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body.data`\"")
    b.append("       },")
    b.append("       \"parts\": [")
    b.append("        \"v1\",")
    b.append("        \"ephemeral\",")
    b.append("        \"convert\"")
    b.append("       ]")
    b.append("      },")
    b.append("      {")
    b.append("       \"args\": {},")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/v1/ephemeral/embed-bridge\",")
    b.append("       \"segments\": [")
    b.append("        {")
    b.append("         \"lit\": \"v1\"")
    b.append("        },")
    b.append("        {")
    b.append("         \"lit\": \"ephemeral\"")
    b.append("        },")
    b.append("        {")
    b.append("         \"lit\": \"embed-bridge\"")
    b.append("        }")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"\$action\": \"ephemeral_bridge\"")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body.data`\"")
    b.append("       },")
    b.append("       \"parts\": [")
    b.append("        \"v1\",")
    b.append("        \"ephemeral\",")
    b.append("        \"embed-bridge\"")
    b.append("       ]")
    b.append("      }")
    b.append("     ]")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"embed\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"name\": \"embeddings\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"One vector per input text, in input order.\",")
    b.append("     \"type\": \"`\$ARRAY`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"model\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"Model that produced the vectors.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"texts\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"Texts to embed.\",")
    b.append("     \"type\": \"`\$ARRAY`\"")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"embed\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"args\": {},")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/v1/embed\",")
    b.append("       \"segments\": [")
    b.append("        {")
    b.append("         \"lit\": \"v1\"")
    b.append("        },")
    b.append("        {")
    b.append("         \"lit\": \"embed\"")
    b.append("        }")
    b.append("       ],")
    b.append("       \"select\": {},")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body.data`\"")
    b.append("       },")
    b.append("       \"parts\": [")
    b.append("        \"v1\",")
    b.append("        \"embed\"")
    b.append("       ]")
    b.append("      },")
    b.append("      {")
    b.append("       \"args\": {},")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/v1/ephemeral/embed\",")
    b.append("       \"segments\": [")
    b.append("        {")
    b.append("         \"lit\": \"v1\"")
    b.append("        },")
    b.append("        {")
    b.append("         \"lit\": \"ephemeral\"")
    b.append("        },")
    b.append("        {")
    b.append("         \"lit\": \"embed\"")
    b.append("        }")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"\$action\": \"ephemeral\"")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body.data`\"")
    b.append("       },")
    b.append("       \"parts\": [")
    b.append("        \"v1\",")
    b.append("        \"ephemeral\",")
    b.append("        \"embed\"")
    b.append("       ]")
    b.append("      }")
    b.append("     ]")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"ephemeral_key\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"name\": \"dailyLimit\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"Calls permitted per day.\",")
    b.append("     \"type\": \"`\$INTEGER`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"dailyUsed\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"Calls already used today.\",")
    b.append("     \"type\": \"`\$INTEGER`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"key\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"The ephemeral API key, prefixed `eph_`.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"format\": \"date-time\",")
    b.append("     \"name\": \"resetsAt\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"When the daily allowance resets.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"ephemeral_key\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"args\": {},")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/v1/ephemeral/key\",")
    b.append("       \"segments\": [")
    b.append("        {")
    b.append("         \"lit\": \"v1\"")
    b.append("        },")
    b.append("        {")
    b.append("         \"lit\": \"ephemeral\"")
    b.append("        },")
    b.append("        {")
    b.append("         \"lit\": \"key\"")
    b.append("        }")
    b.append("       ],")
    b.append("       \"select\": {},")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body.data`\"")
    b.append("       },")
    b.append("       \"parts\": [")
    b.append("        \"v1\",")
    b.append("        \"ephemeral\",")
    b.append("        \"key\"")
    b.append("       ]")
    b.append("      }")
    b.append("     ]")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"model\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"name\": \"eval\",")
    b.append("     \"short\": \"Retrieval-fidelity metrics for a convert model.\",")
    b.append("     \"type\": \"`\$OBJECT`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"executionProvider\",")
    b.append("     \"short\": \"Hardware backend, e.g.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"modelCard\",")
    b.append("     \"short\": \"Convert models only: training provenance and architecture detail.\",")
    b.append("     \"type\": \"`\$OBJECT`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"modelType\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"`embed` for text-to-vector models, `convert` for space-translation models.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"name\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"Model identifier used in requests.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"sequenceLen\",")
    b.append("     \"short\": \"Embed models only: maximum input sequence length.\",")
    b.append("     \"type\": \"`\$INTEGER`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"sourceDim\",")
    b.append("     \"short\": \"Convert models only: source vector dimension.\",")
    b.append("     \"type\": \"`\$INTEGER`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"sourceModel\",")
    b.append("     \"short\": \"Convert models only: the source model space.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"targetDim\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"Dimension of the produced vectors.\",")
    b.append("     \"type\": \"`\$INTEGER`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"targetModel\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"The model space produced.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"model\",")
    b.append("   \"op\": {")
    b.append("    \"list\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"list\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"args\": {},")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"GET\",")
    b.append("       \"orig\": \"/v1/models\",")
    b.append("       \"segments\": [")
    b.append("        {")
    b.append("         \"lit\": \"v1\"")
    b.append("        },")
    b.append("        {")
    b.append("         \"lit\": \"models\"")
    b.append("        }")
    b.append("       ],")
    b.append("       \"select\": {},")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body.data`\"")
    b.append("       },")
    b.append("       \"parts\": [")
    b.append("        \"v1\",")
    b.append("        \"models\"")
    b.append("       ]")
    b.append("      }")
    b.append("     ]")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  }")
    b.append(" }")
    b.append("}")
    return b.toString()
  }
}
