(* Univec SDK client (generated by @voxgig/sdkgen).
 *
 * The SDK "object" is the runtime sdk_client record (see Sdk_types). These
 * constructors wire the embedded config + feature factory (Sdk_config) into
 * the API-agnostic client builders (Sdk_features.make_client_base / sdk_test).
 * Entity accessors return an entity_obj whose CRUD closures run the pipeline. *)

open Voxgig_struct
open Sdk_types
open Sdk_features

(* Construct a live client from options (Noval for defaults). *)
let make (options : value) : sdk_client =
  make_client_base
    ~config:(Sdk_config.make_config ())
    ~make_feature:Sdk_config.make_feature
    options

(* No-argument convenience constructor. *)
let make0 () : sdk_client = make Noval

(* Construct a client in test mode (in-memory mock transport). *)
let test () : sdk_client =
  sdk_test
    ~config:(Sdk_config.make_config ())
    ~make_feature:Sdk_config.make_feature
    Noval Noval

(* Test-mode client with explicit test / sdk options. *)
let test_with (testopts : value) (sdkopts : value) : sdk_client =
  sdk_test
    ~config:(Sdk_config.make_config ())
    ~make_feature:Sdk_config.make_feature
    testopts sdkopts

(* Low-level escape hatches (raw transport call / request preparation). *)
let direct (client : sdk_client) (fetchargs : value) : value =
  Sdk_features.direct client fetchargs

let graphql (client : sdk_client) (query : string) (variables : value)
    (ctrl : value) : value =
  Sdk_features.graphql client query variables ctrl

let prepare (client : sdk_client) (fetchargs : value) : value =
  Sdk_features.prepare client fetchargs

(* Convert entity bound to a client:  convert client entopts *)
let convert (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_convert.make client entopts

(* Embed entity bound to a client:  embed client entopts *)
let embed (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_embed.make client entopts

(* EphemeralKey entity bound to a client:  ephemeral_key client entopts *)
let ephemeral_key (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_ephemeral_key.make client entopts

(* Model entity bound to a client:  model client entopts *)
let model (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_model.make client entopts

(* Entity by name (None for a name this SDK did not generate). *)
let entity (client : sdk_client) (name : string) (entopts : value) : entity_obj option =
  match name with
  | "convert" -> Some (Sdk_entity_convert.make client entopts)
  | "embed" -> Some (Sdk_entity_embed.make client entopts)
  | "ephemeral_key" -> Some (Sdk_entity_ephemeral_key.make client entopts)
  | "model" -> Some (Sdk_entity_model.make client entopts)
  | _ -> None
