-- Univec SDK public client (generated by @voxgig/sdkgen).
--
-- SDK constructors (newSdk / testSdk) and one accessor per entity. Entities
-- are generic — every accessor calls the config-driven F.makeEntity, so the
-- operation pipeline is identical for every entity and every API.

module SdkClient
  ( module SdkTypes
  , newSdk
  , newSdk0
  , testSdk
  , testSdk0
  , convert
  , embed
  , ephemeral_key
  , model
  ) where

import Data.IORef (readIORef)

import VoxgigStruct (Value (..))
import SdkTypes
import SdkConfig (makeConfig, makeFeature)
import qualified SdkFeatures as F

-- | Construct a live SDK client from an options map (Noval for defaults).
newSdk :: Value -> IO Client
newSdk options = do
  cfg <- makeConfig
  F.makeClientBase cfg makeFeature options

-- | No-argument convenience constructor.
newSdk0 :: IO Client
newSdk0 = newSdk VNoval

-- | Construct a test-mode SDK: testSdk testopts sdkopts.
testSdk :: Value -> Value -> IO Client
testSdk testopts sdkopts = do
  cfg <- makeConfig
  F.sdkTest cfg makeFeature testopts sdkopts

-- | No-argument convenience test constructor.
testSdk0 :: IO Client
testSdk0 = testSdk VNoval VNoval

-- | The active client mode ("live" or "test").
clientMode :: Client -> IO String
clientMode = readIORef . clMode

-- | The Convert entity bound to this client.
convert :: Client -> Value -> IO Entity
convert client entopts = F.makeEntity client "convert" entopts

-- | The Embed entity bound to this client.
embed :: Client -> Value -> IO Entity
embed client entopts = F.makeEntity client "embed" entopts

-- | The EphemeralKey entity bound to this client.
ephemeral_key :: Client -> Value -> IO Entity
ephemeral_key client entopts = F.makeEntity client "ephemeral_key" entopts

-- | The Model entity bound to this client.
model :: Client -> Value -> IO Entity
model client entopts = F.makeEntity client "model" entopts

