package voxgig.univecsdk.core;

import java.util.List;
import java.util.Map;

import voxgig.univecsdk.utility.Json;
import voxgig.univecsdk.feature.secrets.sekreto.plugins.Boru;
import voxgig.univecsdk.feature.secrets.sekreto.plugins.Hashicorp;

/** Static SDK configuration and by-name feature construction. */
@SuppressWarnings({"unchecked"})
public final class Config {

  private Config() {}

  public static Map<String, Object> makeConfig() {
    return (Map<String, Object>) Json.parse(configJson());
  }

  // SHARED CONFIG (sdkgen rung L2).
  //
  // The SDK reads the config on every request and never writes to it, so one
  // instance is shared by every client rather than rebuilt per client - the
  // difference between parsing the embedded JSON once and once per client.
  //
  // Initialization-on-demand holder: the JLS guarantees the class initializer
  // runs once, lazily, and safely under concurrency, with no locking on the
  // read path.
  private static final class SharedHolder {
    static final Map<String, Object> VALUE = makeConfig();
  }

  // The process-wide config, built once on first use.
  //
  // The returned map is SHARED: treat it as read-only. Callers that need to
  // mutate should use makeConfig, which always parses a fresh copy.
  public static Map<String, Object> sharedConfig() {
    return SharedHolder.VALUE;
  }

  public static Feature makeFeature(String name) {
    switch (name) {
      case "audit":
        return new voxgig.univecsdk.feature.AuditFeature();
      case "cache":
        return new voxgig.univecsdk.feature.CacheFeature();
      case "clienttrack":
        return new voxgig.univecsdk.feature.ClienttrackFeature();
      case "cost":
        return new voxgig.univecsdk.feature.CostFeature();
      case "debug":
        return new voxgig.univecsdk.feature.DebugFeature();
      case "idempotency":
        return new voxgig.univecsdk.feature.IdempotencyFeature();
      case "log":
        return new voxgig.univecsdk.feature.LogFeature();
      case "metrics":
        return new voxgig.univecsdk.feature.MetricsFeature();
      case "netsim":
        return new voxgig.univecsdk.feature.NetsimFeature();
      case "paging":
        return new voxgig.univecsdk.feature.PagingFeature();
      case "proxy":
        return new voxgig.univecsdk.feature.ProxyFeature();
      case "ratelimit":
        return new voxgig.univecsdk.feature.RatelimitFeature();
      case "rbac":
        return new voxgig.univecsdk.feature.RbacFeature();
      case "retry":
        return new voxgig.univecsdk.feature.RetryFeature();
      case "secrets":
        return new voxgig.univecsdk.feature.SecretsFeature();
      case "streaming":
        return new voxgig.univecsdk.feature.StreamingFeature();
      case "telemetry":
        return new voxgig.univecsdk.feature.TelemetryFeature();
      case "test":
        return new voxgig.univecsdk.feature.TestFeature();
      case "timeout":
        return new voxgig.univecsdk.feature.TimeoutFeature();
      default:
        return new voxgig.univecsdk.feature.BaseFeature();
    }
  }

  /**
   * The plugin definitions the model selected for one feature's chain, as
   * List&lt;Object&gt; so core never names a vendored type. Empty for a
   * feature whose model declares no active plugin group.
   */
  public static List<Object> featurePlugins(String name) {
    switch (name) {
      case "secrets":
        return List.of(Boru.PLUGIN, Hashicorp.PLUGIN);
      default:
        return List.of();
    }
  }

  private static String configJson() {
    StringBuilder b = new StringBuilder();
    b.append("{");
    b.append(" \"main\": {");
    b.append("  \"name\": \"Univec\",");
    b.append("  \"slug\": \"univec\",");
    b.append("  \"version\": \"0.1.2\",");
    b.append("  \"target\": \"java\"");
    b.append(" },");
    b.append(" \"feature\": {");
    b.append("  \"audit\": {");
    b.append("   \"options\": {");
    b.append("    \"active\": false,");
    b.append("    \"actor\": \"anonymous\",");
    b.append("    \"max\": 1000");
    b.append("   },");
    b.append("   \"transport\": \"none\"");
    b.append("  },");
    b.append("  \"cache\": {");
    b.append("   \"options\": {");
    b.append("    \"active\": false,");
    b.append("    \"max\": 256,");
    b.append("    \"methods\": [");
    b.append("     \"GET\"");
    b.append("    ],");
    b.append("    \"ttl\": 5000");
    b.append("   },");
    b.append("   \"transport\": \"wrap\"");
    b.append("  },");
    b.append("  \"clienttrack\": {");
    b.append("   \"options\": {");
    b.append("    \"active\": false,");
    b.append("    \"clientVersion\": \"0.0.1\"");
    b.append("   },");
    b.append("   \"transport\": \"none\"");
    b.append("  },");
    b.append("  \"cost\": {");
    b.append("   \"options\": {");
    b.append("    \"active\": false,");
    b.append("    \"budget\": 0,");
    b.append("    \"currency\": \"USD\",");
    b.append("    \"header\": \"\",");
    b.append("    \"onBudget\": \"warn\",");
    b.append("    \"path\": \"\",");
    b.append("    \"perUnit\": 0,");
    b.append("    \"rates\": {},");
    b.append("    \"unit\": 0");
    b.append("   },");
    b.append("   \"transport\": \"wrap\"");
    b.append("  },");
    b.append("  \"debug\": {");
    b.append("   \"options\": {");
    b.append("    \"active\": false,");
    b.append("    \"max\": 100,");
    b.append("    \"redact\": [");
    b.append("     \"authorization\",");
    b.append("     \"cookie\",");
    b.append("     \"set-cookie\",");
    b.append("     \"api-key\",");
    b.append("     \"apikey\",");
    b.append("     \"x-api-key\",");
    b.append("     \"idempotency-key\"");
    b.append("    ]");
    b.append("   },");
    b.append("   \"transport\": \"none\"");
    b.append("  },");
    b.append("  \"idempotency\": {");
    b.append("   \"options\": {");
    b.append("    \"active\": false,");
    b.append("    \"header\": \"Idempotency-Key\",");
    b.append("    \"methods\": [");
    b.append("     \"POST\",");
    b.append("     \"PUT\",");
    b.append("     \"PATCH\",");
    b.append("     \"DELETE\"");
    b.append("    ],");
    b.append("    \"ops\": [");
    b.append("     \"create\",");
    b.append("     \"update\",");
    b.append("     \"remove\"");
    b.append("    ]");
    b.append("   },");
    b.append("   \"transport\": \"none\"");
    b.append("  },");
    b.append("  \"log\": {");
    b.append("   \"options\": {");
    b.append("    \"active\": true");
    b.append("   },");
    b.append("   \"transport\": \"none\"");
    b.append("  },");
    b.append("  \"metrics\": {");
    b.append("   \"options\": {");
    b.append("    \"active\": false");
    b.append("   },");
    b.append("   \"transport\": \"none\"");
    b.append("  },");
    b.append("  \"netsim\": {");
    b.append("   \"options\": {");
    b.append("    \"active\": false,");
    b.append("    \"errorTimes\": 0,");
    b.append("    \"failEvery\": 0,");
    b.append("    \"failRate\": 0,");
    b.append("    \"failStatus\": 503,");
    b.append("    \"failTimes\": 0,");
    b.append("    \"latency\": 0,");
    b.append("    \"offline\": false,");
    b.append("    \"rateLimitTimes\": 0,");
    b.append("    \"retryAfter\": 0,");
    b.append("    \"seed\": 1");
    b.append("   },");
    b.append("   \"transport\": \"wrap\"");
    b.append("  },");
    b.append("  \"paging\": {");
    b.append("   \"options\": {");
    b.append("    \"active\": false,");
    b.append("    \"afterVar\": \"after\",");
    b.append("    \"cursorParam\": \"cursor\",");
    b.append("    \"firstVar\": \"first\",");
    b.append("    \"limitParam\": \"limit\",");
    b.append("    \"pageParam\": \"page\",");
    b.append("    \"startPage\": 1");
    b.append("   },");
    b.append("   \"transport\": \"none\"");
    b.append("  },");
    b.append("  \"proxy\": {");
    b.append("   \"options\": {");
    b.append("    \"active\": false,");
    b.append("    \"fromEnv\": false,");
    b.append("    \"noProxy\": [],");
    b.append("    \"url\": \"\"");
    b.append("   },");
    b.append("   \"transport\": \"wrap\"");
    b.append("  },");
    b.append("  \"ratelimit\": {");
    b.append("   \"options\": {");
    b.append("    \"active\": false,");
    b.append("    \"burst\": 5,");
    b.append("    \"rate\": 5");
    b.append("   },");
    b.append("   \"transport\": \"wrap\"");
    b.append("  },");
    b.append("  \"rbac\": {");
    b.append("   \"options\": {");
    b.append("    \"active\": false,");
    b.append("    \"deny\": false,");
    b.append("    \"permissions\": [],");
    b.append("    \"rules\": {}");
    b.append("   },");
    b.append("   \"transport\": \"none\"");
    b.append("  },");
    b.append("  \"retry\": {");
    b.append("   \"options\": {");
    b.append("    \"active\": false,");
    b.append("    \"factor\": 2,");
    b.append("    \"maxDelay\": 2000,");
    b.append("    \"minDelay\": 50,");
    b.append("    \"retries\": 2,");
    b.append("    \"statuses\": [");
    b.append("     408,");
    b.append("     425,");
    b.append("     429,");
    b.append("     500,");
    b.append("     502,");
    b.append("     503,");
    b.append("     504");
    b.append("    ]");
    b.append("   },");
    b.append("   \"transport\": \"wrap\"");
    b.append("  },");
    b.append("  \"secrets\": {");
    b.append("   \"options\": {");
    b.append("    \"active\": false,");
    b.append("    \"cache\": true,");
    b.append("    \"exchange\": {");
    b.append("     \"active\": false,");
    b.append("     \"method\": \"POST\",");
    b.append("     \"path\": \"auth/token\",");
    b.append("     \"refresh\": \"\",");
    b.append("     \"request\": \"refresh_token\",");
    b.append("     \"response\": \"access_token\",");
    b.append("     \"retries\": 1,");
    b.append("     \"statuses\": [");
    b.append("      401");
    b.append("     ]");
    b.append("    },");
    b.append("    \"name\": \"univec\",");
    b.append("    \"providers\": [");
    b.append("     {");
    b.append("      \"kind\": \"boru\",");
    b.append("      \"namespace\": \"sdk\"");
    b.append("     }");
    b.append("    ]");
    b.append("   },");
    b.append("   \"transport\": \"wrap\"");
    b.append("  },");
    b.append("  \"streaming\": {");
    b.append("   \"options\": {");
    b.append("    \"active\": false,");
    b.append("    \"chunkDelay\": 0,");
    b.append("    \"chunkSize\": 0");
    b.append("   },");
    b.append("   \"transport\": \"none\"");
    b.append("  },");
    b.append("  \"telemetry\": {");
    b.append("   \"options\": {");
    b.append("    \"active\": false");
    b.append("   },");
    b.append("   \"transport\": \"none\"");
    b.append("  },");
    b.append("  \"test\": {");
    b.append("   \"options\": {");
    b.append("    \"active\": false");
    b.append("   },");
    b.append("   \"transport\": \"base\"");
    b.append("  },");
    b.append("  \"timeout\": {");
    b.append("   \"options\": {");
    b.append("    \"active\": false,");
    b.append("    \"ms\": 30000");
    b.append("   },");
    b.append("   \"transport\": \"wrap\"");
    b.append("  }");
    b.append(" },");
    b.append(" \"options\": {");
    b.append("  \"base\": \"https://api.univec.ai\",");
    b.append("  \"auth\": {");
    b.append("   \"prefix\": \"Bearer\"");
    b.append("  },");
    b.append("  \"headers\": {");
    b.append("   \"content-type\": \"application/json\"");
    b.append("  },");
    b.append("  \"entity\": {");
    b.append("   \"convert\": {},");
    b.append("   \"embed\": {},");
    b.append("   \"ephemeral_key\": {},");
    b.append("   \"model\": {}");
    b.append("  }");
    b.append(" },");
    b.append(" \"entity\": {");
    b.append("  \"convert\": {");
    b.append("   \"fields\": [");
    b.append("    {");
    b.append("     \"name\": \"bridge_model\",");
    b.append("     \"req\": true,");
    b.append("     \"short\": \"Embed model used to vectorise the text before translation.\",");
    b.append("     \"type\": \"`$STRING`\"");
    b.append("    },");
    b.append("    {");
    b.append("     \"name\": \"embeddings\",");
    b.append("     \"req\": true,");
    b.append("     \"short\": \"Translated vectors, in the target model's dimension.\",");
    b.append("     \"type\": \"`$ARRAY`\"");
    b.append("    },");
    b.append("    {");
    b.append("     \"name\": \"source_model\",");
    b.append("     \"req\": true,");
    b.append("     \"short\": \"Model space the supplied vectors are currently in.\",");
    b.append("     \"type\": \"`$STRING`\"");
    b.append("    },");
    b.append("    {");
    b.append("     \"name\": \"target_model\",");
    b.append("     \"req\": true,");
    b.append("     \"short\": \"Model space to translate into.\",");
    b.append("     \"type\": \"`$STRING`\"");
    b.append("    },");
    b.append("    {");
    b.append("     \"name\": \"texts\",");
    b.append("     \"req\": true,");
    b.append("     \"short\": \"Texts to embed and translate.\",");
    b.append("     \"type\": \"`$ARRAY`\"");
    b.append("    }");
    b.append("   ],");
    b.append("   \"name\": \"convert\",");
    b.append("   \"op\": {");
    b.append("    \"create\": {");
    b.append("     \"input\": \"data\",");
    b.append("     \"name\": \"create\",");
    b.append("     \"points\": [");
    b.append("      {");
    b.append("       \"args\": {},");
    b.append("       \"kind\": \"http\",");
    b.append("       \"method\": \"POST\",");
    b.append("       \"orig\": \"/v1/convert\",");
    b.append("       \"segments\": [");
    b.append("        {");
    b.append("         \"lit\": \"v1\"");
    b.append("        },");
    b.append("        {");
    b.append("         \"lit\": \"convert\"");
    b.append("        }");
    b.append("       ],");
    b.append("       \"select\": {},");
    b.append("       \"transform\": {");
    b.append("        \"req\": \"`reqdata`\",");
    b.append("        \"res\": \"`body.data`\"");
    b.append("       },");
    b.append("       \"parts\": [");
    b.append("        \"v1\",");
    b.append("        \"convert\"");
    b.append("       ]");
    b.append("      },");
    b.append("      {");
    b.append("       \"args\": {},");
    b.append("       \"kind\": \"http\",");
    b.append("       \"method\": \"POST\",");
    b.append("       \"orig\": \"/v1/embed-bridge\",");
    b.append("       \"segments\": [");
    b.append("        {");
    b.append("         \"lit\": \"v1\"");
    b.append("        },");
    b.append("        {");
    b.append("         \"lit\": \"embed-bridge\"");
    b.append("        }");
    b.append("       ],");
    b.append("       \"select\": {");
    b.append("        \"$action\": \"bridge\"");
    b.append("       },");
    b.append("       \"transform\": {");
    b.append("        \"req\": \"`reqdata`\",");
    b.append("        \"res\": \"`body.data`\"");
    b.append("       },");
    b.append("       \"parts\": [");
    b.append("        \"v1\",");
    b.append("        \"embed-bridge\"");
    b.append("       ]");
    b.append("      },");
    b.append("      {");
    b.append("       \"args\": {},");
    b.append("       \"kind\": \"http\",");
    b.append("       \"method\": \"POST\",");
    b.append("       \"orig\": \"/v1/ephemeral/convert\",");
    b.append("       \"segments\": [");
    b.append("        {");
    b.append("         \"lit\": \"v1\"");
    b.append("        },");
    b.append("        {");
    b.append("         \"lit\": \"ephemeral\"");
    b.append("        },");
    b.append("        {");
    b.append("         \"lit\": \"convert\"");
    b.append("        }");
    b.append("       ],");
    b.append("       \"select\": {");
    b.append("        \"$action\": \"ephemeral\"");
    b.append("       },");
    b.append("       \"transform\": {");
    b.append("        \"req\": \"`reqdata`\",");
    b.append("        \"res\": \"`body.data`\"");
    b.append("       },");
    b.append("       \"parts\": [");
    b.append("        \"v1\",");
    b.append("        \"ephemeral\",");
    b.append("        \"convert\"");
    b.append("       ]");
    b.append("      },");
    b.append("      {");
    b.append("       \"args\": {},");
    b.append("       \"kind\": \"http\",");
    b.append("       \"method\": \"POST\",");
    b.append("       \"orig\": \"/v1/ephemeral/embed-bridge\",");
    b.append("       \"segments\": [");
    b.append("        {");
    b.append("         \"lit\": \"v1\"");
    b.append("        },");
    b.append("        {");
    b.append("         \"lit\": \"ephemeral\"");
    b.append("        },");
    b.append("        {");
    b.append("         \"lit\": \"embed-bridge\"");
    b.append("        }");
    b.append("       ],");
    b.append("       \"select\": {");
    b.append("        \"$action\": \"ephemeral_bridge\"");
    b.append("       },");
    b.append("       \"transform\": {");
    b.append("        \"req\": \"`reqdata`\",");
    b.append("        \"res\": \"`body.data`\"");
    b.append("       },");
    b.append("       \"parts\": [");
    b.append("        \"v1\",");
    b.append("        \"ephemeral\",");
    b.append("        \"embed-bridge\"");
    b.append("       ]");
    b.append("      }");
    b.append("     ]");
    b.append("    }");
    b.append("   },");
    b.append("   \"relations\": {");
    b.append("    \"ancestors\": []");
    b.append("   }");
    b.append("  },");
    b.append("  \"embed\": {");
    b.append("   \"fields\": [");
    b.append("    {");
    b.append("     \"name\": \"embeddings\",");
    b.append("     \"req\": true,");
    b.append("     \"short\": \"One vector per input text, in input order.\",");
    b.append("     \"type\": \"`$ARRAY`\"");
    b.append("    },");
    b.append("    {");
    b.append("     \"name\": \"model\",");
    b.append("     \"req\": true,");
    b.append("     \"short\": \"Model that produced the vectors.\",");
    b.append("     \"type\": \"`$STRING`\"");
    b.append("    },");
    b.append("    {");
    b.append("     \"name\": \"texts\",");
    b.append("     \"req\": true,");
    b.append("     \"short\": \"Texts to embed.\",");
    b.append("     \"type\": \"`$ARRAY`\"");
    b.append("    }");
    b.append("   ],");
    b.append("   \"name\": \"embed\",");
    b.append("   \"op\": {");
    b.append("    \"create\": {");
    b.append("     \"input\": \"data\",");
    b.append("     \"name\": \"create\",");
    b.append("     \"points\": [");
    b.append("      {");
    b.append("       \"args\": {},");
    b.append("       \"kind\": \"http\",");
    b.append("       \"method\": \"POST\",");
    b.append("       \"orig\": \"/v1/embed\",");
    b.append("       \"segments\": [");
    b.append("        {");
    b.append("         \"lit\": \"v1\"");
    b.append("        },");
    b.append("        {");
    b.append("         \"lit\": \"embed\"");
    b.append("        }");
    b.append("       ],");
    b.append("       \"select\": {},");
    b.append("       \"transform\": {");
    b.append("        \"req\": \"`reqdata`\",");
    b.append("        \"res\": \"`body.data`\"");
    b.append("       },");
    b.append("       \"parts\": [");
    b.append("        \"v1\",");
    b.append("        \"embed\"");
    b.append("       ]");
    b.append("      },");
    b.append("      {");
    b.append("       \"args\": {},");
    b.append("       \"kind\": \"http\",");
    b.append("       \"method\": \"POST\",");
    b.append("       \"orig\": \"/v1/ephemeral/embed\",");
    b.append("       \"segments\": [");
    b.append("        {");
    b.append("         \"lit\": \"v1\"");
    b.append("        },");
    b.append("        {");
    b.append("         \"lit\": \"ephemeral\"");
    b.append("        },");
    b.append("        {");
    b.append("         \"lit\": \"embed\"");
    b.append("        }");
    b.append("       ],");
    b.append("       \"select\": {");
    b.append("        \"$action\": \"ephemeral\"");
    b.append("       },");
    b.append("       \"transform\": {");
    b.append("        \"req\": \"`reqdata`\",");
    b.append("        \"res\": \"`body.data`\"");
    b.append("       },");
    b.append("       \"parts\": [");
    b.append("        \"v1\",");
    b.append("        \"ephemeral\",");
    b.append("        \"embed\"");
    b.append("       ]");
    b.append("      }");
    b.append("     ]");
    b.append("    }");
    b.append("   },");
    b.append("   \"relations\": {");
    b.append("    \"ancestors\": []");
    b.append("   }");
    b.append("  },");
    b.append("  \"ephemeral_key\": {");
    b.append("   \"fields\": [");
    b.append("    {");
    b.append("     \"name\": \"dailyLimit\",");
    b.append("     \"req\": true,");
    b.append("     \"short\": \"Calls permitted per day.\",");
    b.append("     \"type\": \"`$INTEGER`\"");
    b.append("    },");
    b.append("    {");
    b.append("     \"name\": \"dailyUsed\",");
    b.append("     \"req\": true,");
    b.append("     \"short\": \"Calls already used today.\",");
    b.append("     \"type\": \"`$INTEGER`\"");
    b.append("    },");
    b.append("    {");
    b.append("     \"name\": \"key\",");
    b.append("     \"req\": true,");
    b.append("     \"short\": \"The ephemeral API key, prefixed `eph_`.\",");
    b.append("     \"type\": \"`$STRING`\"");
    b.append("    },");
    b.append("    {");
    b.append("     \"format\": \"date-time\",");
    b.append("     \"name\": \"resetsAt\",");
    b.append("     \"req\": true,");
    b.append("     \"short\": \"When the daily allowance resets.\",");
    b.append("     \"type\": \"`$STRING`\"");
    b.append("    }");
    b.append("   ],");
    b.append("   \"name\": \"ephemeral_key\",");
    b.append("   \"op\": {");
    b.append("    \"create\": {");
    b.append("     \"input\": \"data\",");
    b.append("     \"name\": \"create\",");
    b.append("     \"points\": [");
    b.append("      {");
    b.append("       \"args\": {},");
    b.append("       \"kind\": \"http\",");
    b.append("       \"method\": \"POST\",");
    b.append("       \"orig\": \"/v1/ephemeral/key\",");
    b.append("       \"segments\": [");
    b.append("        {");
    b.append("         \"lit\": \"v1\"");
    b.append("        },");
    b.append("        {");
    b.append("         \"lit\": \"ephemeral\"");
    b.append("        },");
    b.append("        {");
    b.append("         \"lit\": \"key\"");
    b.append("        }");
    b.append("       ],");
    b.append("       \"select\": {},");
    b.append("       \"transform\": {");
    b.append("        \"req\": \"`reqdata`\",");
    b.append("        \"res\": \"`body.data`\"");
    b.append("       },");
    b.append("       \"parts\": [");
    b.append("        \"v1\",");
    b.append("        \"ephemeral\",");
    b.append("        \"key\"");
    b.append("       ]");
    b.append("      }");
    b.append("     ]");
    b.append("    }");
    b.append("   },");
    b.append("   \"relations\": {");
    b.append("    \"ancestors\": []");
    b.append("   }");
    b.append("  },");
    b.append("  \"model\": {");
    b.append("   \"fields\": [");
    b.append("    {");
    b.append("     \"name\": \"eval\",");
    b.append("     \"short\": \"Retrieval-fidelity metrics for a convert model.\",");
    b.append("     \"type\": \"`$OBJECT`\"");
    b.append("    },");
    b.append("    {");
    b.append("     \"name\": \"executionProvider\",");
    b.append("     \"short\": \"Hardware backend, e.g.\",");
    b.append("     \"type\": \"`$STRING`\"");
    b.append("    },");
    b.append("    {");
    b.append("     \"name\": \"modelCard\",");
    b.append("     \"short\": \"Convert models only: training provenance and architecture detail.\",");
    b.append("     \"type\": \"`$OBJECT`\"");
    b.append("    },");
    b.append("    {");
    b.append("     \"name\": \"modelType\",");
    b.append("     \"req\": true,");
    b.append("     \"short\": \"`embed` for text-to-vector models, `convert` for space-translation models.\",");
    b.append("     \"type\": \"`$STRING`\"");
    b.append("    },");
    b.append("    {");
    b.append("     \"name\": \"name\",");
    b.append("     \"req\": true,");
    b.append("     \"short\": \"Model identifier used in requests.\",");
    b.append("     \"type\": \"`$STRING`\"");
    b.append("    },");
    b.append("    {");
    b.append("     \"name\": \"sequenceLen\",");
    b.append("     \"short\": \"Embed models only: maximum input sequence length.\",");
    b.append("     \"type\": \"`$INTEGER`\"");
    b.append("    },");
    b.append("    {");
    b.append("     \"name\": \"sourceDim\",");
    b.append("     \"short\": \"Convert models only: source vector dimension.\",");
    b.append("     \"type\": \"`$INTEGER`\"");
    b.append("    },");
    b.append("    {");
    b.append("     \"name\": \"sourceModel\",");
    b.append("     \"short\": \"Convert models only: the source model space.\",");
    b.append("     \"type\": \"`$STRING`\"");
    b.append("    },");
    b.append("    {");
    b.append("     \"name\": \"targetDim\",");
    b.append("     \"req\": true,");
    b.append("     \"short\": \"Dimension of the produced vectors.\",");
    b.append("     \"type\": \"`$INTEGER`\"");
    b.append("    },");
    b.append("    {");
    b.append("     \"name\": \"targetModel\",");
    b.append("     \"req\": true,");
    b.append("     \"short\": \"The model space produced.\",");
    b.append("     \"type\": \"`$STRING`\"");
    b.append("    }");
    b.append("   ],");
    b.append("   \"name\": \"model\",");
    b.append("   \"op\": {");
    b.append("    \"list\": {");
    b.append("     \"input\": \"data\",");
    b.append("     \"name\": \"list\",");
    b.append("     \"points\": [");
    b.append("      {");
    b.append("       \"args\": {},");
    b.append("       \"kind\": \"http\",");
    b.append("       \"method\": \"GET\",");
    b.append("       \"orig\": \"/v1/models\",");
    b.append("       \"segments\": [");
    b.append("        {");
    b.append("         \"lit\": \"v1\"");
    b.append("        },");
    b.append("        {");
    b.append("         \"lit\": \"models\"");
    b.append("        }");
    b.append("       ],");
    b.append("       \"select\": {},");
    b.append("       \"transform\": {");
    b.append("        \"req\": \"`reqdata`\",");
    b.append("        \"res\": \"`body.data`\"");
    b.append("       },");
    b.append("       \"parts\": [");
    b.append("        \"v1\",");
    b.append("        \"models\"");
    b.append("       ]");
    b.append("      }");
    b.append("     ]");
    b.append("    }");
    b.append("   },");
    b.append("   \"relations\": {");
    b.append("    \"ancestors\": []");
    b.append("   }");
    b.append("  }");
    b.append(" }");
    b.append("}");
    return b.toString();
  }
}
