;; Univec SDK public API (generated by @voxgig/sdkgen).
(ns sdk.api
  (:require [sdk.client :as client]
            [sdk.entity.convert :as e-convert]
            [sdk.entity.embed :as e-embed]
            [sdk.entity.ephemeral_key :as e-ephemeral_key]
            [sdk.entity.model :as e-model]))

(def make-sdk client/make-sdk)
(def test-sdk client/test-sdk)
(def direct client/direct)
(def graphql client/graphql)
(def prepare client/prepare)
(def options-map client/options-map)

;; Convert accessor: (convert client data)
(defn convert [client data] (e-convert/make client data))

;; Embed accessor: (embed client data)
(defn embed [client data] (e-embed/make client data))

;; EphemeralKey accessor: (ephemeral_key client data)
(defn ephemeral_key [client data] (e-ephemeral_key/make client data))

;; Model accessor: (model client data)
(defn model [client data] (e-model/make client data))
