;; Univec SDK configuration (generated by @voxgig/sdkgen).
(ns sdk.config
  (:require [voxgig.struct :as vs]))

(defn make-config []
  (vs/jm
    "entity" (vs/jm
      "convert" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "bridge_model"
            "req" true
            "short" "Embed model used to vectorise the text before translation."
            "type" "`$STRING`")
          (vs/jm
            "name" "embeddings"
            "req" true
            "short" "Translated vectors, in the target model's dimension."
            "type" "`$ARRAY`")
          (vs/jm
            "name" "source_model"
            "req" true
            "short" "Model space the supplied vectors are currently in."
            "type" "`$STRING`")
          (vs/jm
            "name" "target_model"
            "req" true
            "short" "Model space to translate into."
            "type" "`$STRING`")
          (vs/jm
            "name" "texts"
            "req" true
            "short" "Texts to embed and translate."
            "type" "`$ARRAY`"))
        "name" "convert"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/v1/convert"
                "parts" (vs/jt
                  "v1"
                  "convert")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body.data`"))
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/v1/embed-bridge"
                "parts" (vs/jt
                  "v1"
                  "embed-bridge")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body.data`"))
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/v1/ephemeral/convert"
                "parts" (vs/jt
                  "v1"
                  "ephemeral"
                  "convert")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body.data`"))
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/v1/ephemeral/embed-bridge"
                "parts" (vs/jt
                  "v1"
                  "ephemeral"
                  "embed-bridge")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body.data`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "embed" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "embeddings"
            "req" true
            "short" "One vector per input text, in input order."
            "type" "`$ARRAY`")
          (vs/jm
            "name" "model"
            "req" true
            "short" "Model that produced the vectors."
            "type" "`$STRING`")
          (vs/jm
            "name" "texts"
            "req" true
            "short" "Texts to embed."
            "type" "`$ARRAY`"))
        "name" "embed"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/v1/embed"
                "parts" (vs/jt
                  "v1"
                  "embed")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body.data`"))
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/v1/ephemeral/embed"
                "parts" (vs/jt
                  "v1"
                  "ephemeral"
                  "embed")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body.data`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "ephemeral_key" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "dailyLimit"
            "req" true
            "short" "Calls permitted per day."
            "type" "`$INTEGER`")
          (vs/jm
            "name" "dailyUsed"
            "req" true
            "short" "Calls already used today."
            "type" "`$INTEGER`")
          (vs/jm
            "name" "key"
            "req" true
            "short" "The ephemeral API key, prefixed `eph_`."
            "type" "`$STRING`")
          (vs/jm
            "name" "resetsAt"
            "req" true
            "short" "When the daily allowance resets."
            "type" "`$STRING`"))
        "name" "ephemeral_key"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/v1/ephemeral/key"
                "parts" (vs/jt
                  "v1"
                  "ephemeral"
                  "key")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body.data`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "model" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "eval"
            "short" "Retrieval-fidelity metrics for a convert model."
            "type" "`$OBJECT`")
          (vs/jm
            "name" "executionProvider"
            "short" "Hardware backend, e.g."
            "type" "`$STRING`")
          (vs/jm
            "name" "modelCard"
            "short" "Convert models only: training provenance and architecture detail."
            "type" "`$OBJECT`")
          (vs/jm
            "name" "modelType"
            "req" true
            "short" "`embed` for text-to-vector models, `convert` for space-translation models."
            "type" "`$STRING`")
          (vs/jm
            "name" "name"
            "req" true
            "short" "Model identifier used in requests."
            "type" "`$STRING`")
          (vs/jm
            "name" "sequenceLen"
            "short" "Embed models only: maximum input sequence length."
            "type" "`$INTEGER`")
          (vs/jm
            "name" "sourceDim"
            "short" "Convert models only: source vector dimension."
            "type" "`$INTEGER`")
          (vs/jm
            "name" "sourceModel"
            "short" "Convert models only: the source model space."
            "type" "`$STRING`")
          (vs/jm
            "name" "targetDim"
            "req" true
            "short" "Dimension of the produced vectors."
            "type" "`$INTEGER`")
          (vs/jm
            "name" "targetModel"
            "req" true
            "short" "The model space produced."
            "type" "`$STRING`"))
        "name" "model"
        "op" (vs/jm
          "list" (vs/jm
            "input" "data"
            "name" "list"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "GET"
                "orig" "/v1/models"
                "parts" (vs/jt
                  "v1"
                  "models")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body.data`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt))))
    "feature" (vs/jm
      "test" (vs/jm
        "options" (vs/jm
          "active" false)
        "transport" "base"))
    "main" (vs/jm
      "name" "Univec"
      "slug" "univec"
      "target" "clojure"
      "version" "0.1.1")
    "options" (vs/jm
      "auth" (vs/jm
        "prefix" "Bearer")
      "base" "https://api.univec.ai"
      "entity" (vs/jm
        "convert" (vs/jm)
        "embed" (vs/jm)
        "ephemeral_key" (vs/jm)
        "model" (vs/jm))
      "headers" (vs/jm
        "content-type" "application/json"))))
