;; Univec SDK configuration (generated by @voxgig/sdkgen).
(ns sdk.config
  (:require [voxgig.struct :as vs]
            [voxgig.sekreto.plugins.boru :as p-boru]
            [voxgig.sekreto.plugins.hashicorp :as p-hashicorp]
            [sdk.feature.secrets :as fx-secrets]))

(defn make-config []
  (vs/jm
    "entity" (vs/jm
      "convert" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "embeddings"
            "req" true
            "short" "Translated vectors, in the target model's dimension."
            "type" "`$ARRAY`")
          (vs/jm
            "name" "source_model"
            "req" true
            "short" "Model space the supplied vectors are currently in."
            "type" "`$STRING`")
          (vs/jm
            "name" "target_model"
            "req" true
            "short" "Model space to translate into."
            "type" "`$STRING`"))
        "name" "convert"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "live" (vs/jm
                  "assert" (vs/jm
                    "equal" (vs/jm
                      "source_model" (vs/jm
                        "from" "models"
                        "path" "sourceModel"
                        "related" (vs/jm
                          "foreign" "name"
                          "from" "models"
                          "local" "sourceModel"
                          "where" (vs/jm
                            "modelType" "embed"))
                        "where" (vs/jm
                          "modelType" "convert"))
                      "target_model" (vs/jm
                        "from" "models"
                        "path" "targetModel"
                        "related" (vs/jm
                          "foreign" "name"
                          "from" "models"
                          "local" "sourceModel"
                          "where" (vs/jm
                            "modelType" "embed"))
                        "where" (vs/jm
                          "modelType" "convert")))
                    "vectors" (vs/jm
                      "count" 1
                      "dimension" (vs/jm
                        "from" "models"
                        "path" "targetDim"
                        "related" (vs/jm
                          "foreign" "name"
                          "from" "models"
                          "local" "sourceModel"
                          "where" (vs/jm
                            "modelType" "embed"))
                        "where" (vs/jm
                          "modelType" "convert"))
                      "path" "embeddings"))
                  "auth" "account"
                  "id" "account-convert"
                  "input" (vs/jm
                    "embeddings" (vs/jm
                      "from" "account-embed"
                      "path" "embeddings")
                    "source_model" (vs/jm
                      "from" "models"
                      "path" "sourceModel"
                      "related" (vs/jm
                        "foreign" "name"
                        "from" "models"
                        "local" "sourceModel"
                        "where" (vs/jm
                          "modelType" "embed"))
                      "where" (vs/jm
                        "modelType" "convert"))
                    "target_model" (vs/jm
                      "from" "models"
                      "path" "targetModel"
                      "related" (vs/jm
                        "foreign" "name"
                        "from" "models"
                        "local" "sourceModel"
                        "where" (vs/jm
                          "modelType" "embed"))
                      "where" (vs/jm
                        "modelType" "convert"))))
                "method" "POST"
                "orig" "/v1/convert"
                "parts" (vs/jt
                  "v1"
                  "convert")
                "segments" (vs/jt
                  (vs/jm
                    "lit" "v1")
                  (vs/jm
                    "lit" "convert"))
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body.data`"))
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "live" (vs/jm
                  "assert" (vs/jm
                    "equal" (vs/jm
                      "bridge_model" (vs/jm
                        "from" "models"
                        "path" "sourceModel"
                        "related" (vs/jm
                          "foreign" "name"
                          "from" "models"
                          "local" "sourceModel"
                          "where" (vs/jm
                            "modelType" "embed"))
                        "where" (vs/jm
                          "modelType" "convert"))
                      "target_model" (vs/jm
                        "from" "models"
                        "path" "targetModel"
                        "related" (vs/jm
                          "foreign" "name"
                          "from" "models"
                          "local" "sourceModel"
                          "where" (vs/jm
                            "modelType" "embed"))
                        "where" (vs/jm
                          "modelType" "convert")))
                    "vectors" (vs/jm
                      "count" 1
                      "dimension" (vs/jm
                        "from" "models"
                        "path" "targetDim"
                        "related" (vs/jm
                          "foreign" "name"
                          "from" "models"
                          "local" "sourceModel"
                          "where" (vs/jm
                            "modelType" "embed"))
                        "where" (vs/jm
                          "modelType" "convert"))
                      "path" "embeddings"))
                  "auth" "account"
                  "id" "account-embed-bridge"
                  "input" (vs/jm
                    "bridge_model" (vs/jm
                      "from" "models"
                      "path" "sourceModel"
                      "related" (vs/jm
                        "foreign" "name"
                        "from" "models"
                        "local" "sourceModel"
                        "where" (vs/jm
                          "modelType" "embed"))
                      "where" (vs/jm
                        "modelType" "convert"))
                    "target_model" (vs/jm
                      "from" "models"
                      "path" "targetModel"
                      "related" (vs/jm
                        "foreign" "name"
                        "from" "models"
                        "local" "sourceModel"
                        "where" (vs/jm
                          "modelType" "embed"))
                      "where" (vs/jm
                        "modelType" "convert"))
                    "texts" (vs/jt
                      "SDK live coverage test.")))
                "method" "POST"
                "orig" "/v1/embed-bridge"
                "parts" (vs/jt
                  "v1"
                  "embed-bridge")
                "segments" (vs/jt
                  (vs/jm
                    "lit" "v1")
                  (vs/jm
                    "lit" "embed-bridge"))
                "select" (vs/jm
                  "$action" "bridge")
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body.data`"))
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "live" (vs/jm
                  "assert" (vs/jm
                    "equal" (vs/jm
                      "source_model" (vs/jm
                        "from" "models"
                        "path" "sourceModel"
                        "related" (vs/jm
                          "foreign" "name"
                          "from" "models"
                          "local" "sourceModel"
                          "where" (vs/jm
                            "modelType" "embed"))
                        "where" (vs/jm
                          "modelType" "convert"))
                      "target_model" (vs/jm
                        "from" "models"
                        "path" "targetModel"
                        "related" (vs/jm
                          "foreign" "name"
                          "from" "models"
                          "local" "sourceModel"
                          "where" (vs/jm
                            "modelType" "embed"))
                        "where" (vs/jm
                          "modelType" "convert")))
                    "vectors" (vs/jm
                      "count" 1
                      "dimension" (vs/jm
                        "from" "models"
                        "path" "targetDim"
                        "related" (vs/jm
                          "foreign" "name"
                          "from" "models"
                          "local" "sourceModel"
                          "where" (vs/jm
                            "modelType" "embed"))
                        "where" (vs/jm
                          "modelType" "convert"))
                      "path" "embeddings"))
                  "auth" "issued"
                  "credential" (vs/jm
                    "from" "key"
                    "path" "key")
                  "id" "ephemeral-convert"
                  "input" (vs/jm
                    "embeddings" (vs/jm
                      "from" "ephemeral-embed"
                      "path" "embeddings")
                    "source_model" (vs/jm
                      "from" "models"
                      "path" "sourceModel"
                      "related" (vs/jm
                        "foreign" "name"
                        "from" "models"
                        "local" "sourceModel"
                        "where" (vs/jm
                          "modelType" "embed"))
                      "where" (vs/jm
                        "modelType" "convert"))
                    "target_model" (vs/jm
                      "from" "models"
                      "path" "targetModel"
                      "related" (vs/jm
                        "foreign" "name"
                        "from" "models"
                        "local" "sourceModel"
                        "where" (vs/jm
                          "modelType" "embed"))
                      "where" (vs/jm
                        "modelType" "convert"))))
                "method" "POST"
                "orig" "/v1/ephemeral/convert"
                "parts" (vs/jt
                  "v1"
                  "ephemeral"
                  "convert")
                "segments" (vs/jt
                  (vs/jm
                    "lit" "v1")
                  (vs/jm
                    "lit" "ephemeral")
                  (vs/jm
                    "lit" "convert"))
                "select" (vs/jm
                  "$action" "ephemeral")
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body.data`"))
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "live" (vs/jm
                  "assert" (vs/jm
                    "equal" (vs/jm
                      "bridge_model" (vs/jm
                        "from" "models"
                        "path" "sourceModel"
                        "related" (vs/jm
                          "foreign" "name"
                          "from" "models"
                          "local" "sourceModel"
                          "where" (vs/jm
                            "modelType" "embed"))
                        "where" (vs/jm
                          "modelType" "convert"))
                      "target_model" (vs/jm
                        "from" "models"
                        "path" "targetModel"
                        "related" (vs/jm
                          "foreign" "name"
                          "from" "models"
                          "local" "sourceModel"
                          "where" (vs/jm
                            "modelType" "embed"))
                        "where" (vs/jm
                          "modelType" "convert")))
                    "vectors" (vs/jm
                      "count" 1
                      "dimension" (vs/jm
                        "from" "models"
                        "path" "targetDim"
                        "related" (vs/jm
                          "foreign" "name"
                          "from" "models"
                          "local" "sourceModel"
                          "where" (vs/jm
                            "modelType" "embed"))
                        "where" (vs/jm
                          "modelType" "convert"))
                      "path" "embeddings"))
                  "auth" "issued"
                  "credential" (vs/jm
                    "from" "key"
                    "path" "key")
                  "id" "ephemeral-embed-bridge"
                  "input" (vs/jm
                    "bridge_model" (vs/jm
                      "from" "models"
                      "path" "sourceModel"
                      "related" (vs/jm
                        "foreign" "name"
                        "from" "models"
                        "local" "sourceModel"
                        "where" (vs/jm
                          "modelType" "embed"))
                      "where" (vs/jm
                        "modelType" "convert"))
                    "target_model" (vs/jm
                      "from" "models"
                      "path" "targetModel"
                      "related" (vs/jm
                        "foreign" "name"
                        "from" "models"
                        "local" "sourceModel"
                        "where" (vs/jm
                          "modelType" "embed"))
                      "where" (vs/jm
                        "modelType" "convert"))
                    "texts" (vs/jt
                      "SDK live coverage test.")))
                "method" "POST"
                "orig" "/v1/ephemeral/embed-bridge"
                "parts" (vs/jt
                  "v1"
                  "ephemeral"
                  "embed-bridge")
                "segments" (vs/jt
                  (vs/jm
                    "lit" "v1")
                  (vs/jm
                    "lit" "ephemeral")
                  (vs/jm
                    "lit" "embed-bridge"))
                "select" (vs/jm
                  "$action" "ephemeral_bridge")
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body.data`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "embed" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "embeddings"
            "req" true
            "short" "One vector per input text, in input order."
            "type" "`$ARRAY`")
          (vs/jm
            "name" "model"
            "req" true
            "short" "Model that produced the vectors."
            "type" "`$STRING`")
          (vs/jm
            "name" "texts"
            "req" true
            "short" "Texts to embed."
            "type" "`$ARRAY`"))
        "name" "embed"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "live" (vs/jm
                  "assert" (vs/jm
                    "equal" (vs/jm
                      "model" (vs/jm
                        "from" "models"
                        "path" "sourceModel"
                        "related" (vs/jm
                          "foreign" "name"
                          "from" "models"
                          "local" "sourceModel"
                          "where" (vs/jm
                            "modelType" "embed"))
                        "where" (vs/jm
                          "modelType" "convert")))
                    "vectors" (vs/jm
                      "count" 1
                      "dimension" (vs/jm
                        "from" "models"
                        "path" "sourceDim"
                        "related" (vs/jm
                          "foreign" "name"
                          "from" "models"
                          "local" "sourceModel"
                          "where" (vs/jm
                            "modelType" "embed"))
                        "where" (vs/jm
                          "modelType" "convert"))
                      "path" "embeddings"))
                  "auth" "account"
                  "id" "account-embed"
                  "input" (vs/jm
                    "model" (vs/jm
                      "from" "models"
                      "path" "sourceModel"
                      "related" (vs/jm
                        "foreign" "name"
                        "from" "models"
                        "local" "sourceModel"
                        "where" (vs/jm
                          "modelType" "embed"))
                      "where" (vs/jm
                        "modelType" "convert"))
                    "texts" (vs/jt
                      "SDK live coverage test.")))
                "method" "POST"
                "orig" "/v1/embed"
                "parts" (vs/jt
                  "v1"
                  "embed")
                "segments" (vs/jt
                  (vs/jm
                    "lit" "v1")
                  (vs/jm
                    "lit" "embed"))
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body.data`"))
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "live" (vs/jm
                  "assert" (vs/jm
                    "equal" (vs/jm
                      "model" (vs/jm
                        "from" "models"
                        "path" "sourceModel"
                        "related" (vs/jm
                          "foreign" "name"
                          "from" "models"
                          "local" "sourceModel"
                          "where" (vs/jm
                            "modelType" "embed"))
                        "where" (vs/jm
                          "modelType" "convert")))
                    "vectors" (vs/jm
                      "count" 1
                      "dimension" (vs/jm
                        "from" "models"
                        "path" "sourceDim"
                        "related" (vs/jm
                          "foreign" "name"
                          "from" "models"
                          "local" "sourceModel"
                          "where" (vs/jm
                            "modelType" "embed"))
                        "where" (vs/jm
                          "modelType" "convert"))
                      "path" "embeddings"))
                  "auth" "issued"
                  "credential" (vs/jm
                    "from" "key"
                    "path" "key")
                  "id" "ephemeral-embed"
                  "input" (vs/jm
                    "model" (vs/jm
                      "from" "models"
                      "path" "sourceModel"
                      "related" (vs/jm
                        "foreign" "name"
                        "from" "models"
                        "local" "sourceModel"
                        "where" (vs/jm
                          "modelType" "embed"))
                      "where" (vs/jm
                        "modelType" "convert"))
                    "texts" (vs/jt
                      "SDK live coverage test.")))
                "method" "POST"
                "orig" "/v1/ephemeral/embed"
                "parts" (vs/jt
                  "v1"
                  "ephemeral"
                  "embed")
                "segments" (vs/jt
                  (vs/jm
                    "lit" "v1")
                  (vs/jm
                    "lit" "ephemeral")
                  (vs/jm
                    "lit" "embed"))
                "select" (vs/jm
                  "$action" "ephemeral")
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body.data`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "ephemeral_key" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "dailyLimit"
            "req" true
            "short" "Calls permitted per day."
            "type" "`$INTEGER`")
          (vs/jm
            "name" "dailyUsed"
            "req" true
            "short" "Calls already used today."
            "type" "`$INTEGER`")
          (vs/jm
            "name" "key"
            "req" true
            "short" "The ephemeral API key, prefixed `eph_`."
            "type" "`$STRING`")
          (vs/jm
            "format" "date-time"
            "name" "resetsAt"
            "req" true
            "short" "When the daily allowance resets."
            "type" "`$STRING`"))
        "name" "ephemeral_key"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "live" (vs/jm
                  "assert" (vs/jm
                    "nonempty" (vs/jt
                      "key"))
                  "auth" "public"
                  "id" "key"
                  "retention" "No deletion endpoint; issued key is subject to the service daily allowance")
                "method" "POST"
                "orig" "/v1/ephemeral/key"
                "parts" (vs/jt
                  "v1"
                  "ephemeral"
                  "key")
                "segments" (vs/jt
                  (vs/jm
                    "lit" "v1")
                  (vs/jm
                    "lit" "ephemeral")
                  (vs/jm
                    "lit" "key"))
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body.data`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "model" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "eval"
            "short" "Retrieval-fidelity metrics for a convert model."
            "type" "`$OBJECT`")
          (vs/jm
            "name" "executionProvider"
            "short" "Hardware backend, e.g."
            "type" "`$STRING`")
          (vs/jm
            "name" "modelCard"
            "short" "Convert models only: training provenance and architecture detail."
            "type" "`$OBJECT`")
          (vs/jm
            "name" "modelType"
            "req" true
            "short" "`embed` for text-to-vector models, `convert` for space-translation models."
            "type" "`$STRING`")
          (vs/jm
            "name" "name"
            "req" true
            "short" "Model identifier used in requests."
            "type" "`$STRING`")
          (vs/jm
            "name" "sequenceLen"
            "short" "Embed models only: maximum input sequence length."
            "type" "`$INTEGER`")
          (vs/jm
            "name" "sourceDim"
            "short" "Convert models only: source vector dimension."
            "type" "`$INTEGER`")
          (vs/jm
            "name" "sourceModel"
            "short" "Convert models only: the source model space."
            "type" "`$STRING`")
          (vs/jm
            "name" "targetDim"
            "req" true
            "short" "Dimension of the produced vectors."
            "type" "`$INTEGER`")
          (vs/jm
            "name" "targetModel"
            "req" true
            "short" "The model space produced."
            "type" "`$STRING`"))
        "name" "model"
        "op" (vs/jm
          "list" (vs/jm
            "input" "data"
            "name" "list"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "live" (vs/jm
                  "assert" (vs/jm
                    "nonempty" (vs/jt
                      ""))
                  "auth" "public"
                  "id" "models")
                "method" "GET"
                "orig" "/v1/models"
                "parts" (vs/jt
                  "v1"
                  "models")
                "segments" (vs/jt
                  (vs/jm
                    "lit" "v1")
                  (vs/jm
                    "lit" "models"))
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body.data`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt))))
    "feature" (vs/jm
      "audit" (vs/jm
        "options" (vs/jm
          "active" false
          "actor" "anonymous"
          "max" 1000)
        "optspec" (vs/jm
          "now" "`$FUNCTION`"
          "sink" "`$FUNCTION`")
        "strict" false
        "transport" "none")
      "cache" (vs/jm
        "options" (vs/jm
          "active" false
          "max" 256
          "methods" (vs/jt
            "GET")
          "ttl" 5000)
        "optspec" (vs/jm
          "now" "`$FUNCTION`")
        "strict" false
        "transport" "wrap")
      "clienttrack" (vs/jm
        "options" (vs/jm
          "active" false
          "clientVersion" "0.0.1")
        "optspec" (vs/jm
          "clientName" "`$STRING`"
          "clientVersion" "`$STRING`"
          "headers" "`$MAP`"
          "idgen" "`$FUNCTION`"
          "sessionId" "`$STRING`")
        "strict" false
        "transport" "none")
      "cost" (vs/jm
        "options" (vs/jm
          "active" false
          "budget" 0
          "currency" "USD"
          "header" ""
          "onBudget" "warn"
          "path" ""
          "perUnit" 0
          "rates" (vs/jm)
          "unit" 0)
        "optspec" (vs/jm
          "actor" "`$STRING`"
          "sink" "`$FUNCTION`")
        "strict" false
        "transport" "wrap")
      "debug" (vs/jm
        "options" (vs/jm
          "active" false
          "max" 100
          "redact" (vs/jt
            "authorization"
            "cookie"
            "set-cookie"
            "api-key"
            "apikey"
            "x-api-key"
            "idempotency-key"))
        "optspec" (vs/jm
          "now" "`$FUNCTION`"
          "onEntry" "`$FUNCTION`")
        "strict" false
        "transport" "none")
      "idempotency" (vs/jm
        "options" (vs/jm
          "active" false
          "header" "Idempotency-Key"
          "methods" (vs/jt
            "POST"
            "PUT"
            "PATCH"
            "DELETE")
          "ops" (vs/jt
            "create"
            "update"
            "remove"))
        "optspec" (vs/jm
          "keygen" "`$FUNCTION`")
        "strict" false
        "transport" "none")
      "log" (vs/jm
        "options" (vs/jm
          "active" true)
        "optspec" (vs/jm
          "level" "`$STRING`"
          "logger" "`$ANY`")
        "strict" false
        "transport" "none")
      "metrics" (vs/jm
        "options" (vs/jm
          "active" false)
        "optspec" (vs/jm
          "now" "`$FUNCTION`")
        "strict" false
        "transport" "none")
      "netsim" (vs/jm
        "options" (vs/jm
          "active" false
          "errorTimes" 0
          "failEvery" 0
          "failRate" 0
          "failStatus" 503
          "failTimes" 0
          "latency" 0
          "offline" false
          "rateLimitTimes" 0
          "retryAfter" 0
          "seed" 1)
        "optspec" (vs/jm
          "latency" (vs/jt
            "`$ONE`"
            "`$NUMBER`"
            "`$MAP`")
          "sleep" "`$FUNCTION`")
        "strict" false
        "transport" "wrap")
      "paging" (vs/jm
        "options" (vs/jm
          "active" false
          "afterVar" "after"
          "cursorParam" "cursor"
          "firstVar" "first"
          "limitParam" "limit"
          "pageParam" "page"
          "startPage" 1)
        "optspec" (vs/jm
          "limit" "`$NUMBER`"
          "ops" "`$LIST`")
        "strict" false
        "transport" "none")
      "proxy" (vs/jm
        "options" (vs/jm
          "active" false
          "fromEnv" false
          "noProxy" (vs/jt)
          "url" "")
        "optspec" (vs/jm
          "agent" "`$FUNCTION`")
        "strict" false
        "transport" "wrap")
      "ratelimit" (vs/jm
        "options" (vs/jm
          "active" false
          "burst" 5
          "rate" 5)
        "optspec" (vs/jm
          "now" "`$FUNCTION`"
          "sleep" "`$FUNCTION`")
        "strict" false
        "transport" "wrap")
      "rbac" (vs/jm
        "options" (vs/jm
          "active" false
          "deny" false
          "permissions" (vs/jt)
          "rules" (vs/jm))
        "optspec" (vs/jm)
        "strict" false
        "transport" "none")
      "retry" (vs/jm
        "options" (vs/jm
          "active" false
          "factor" 2
          "maxDelay" 2000
          "minDelay" 50
          "retries" 2
          "statuses" (vs/jt
            408
            425
            429
            500
            502
            503
            504))
        "optspec" (vs/jm
          "jitter" "`$BOOLEAN`"
          "sleep" "`$FUNCTION`")
        "strict" false
        "transport" "wrap")
      "secrets" (vs/jm
        "options" (vs/jm
          "active" false
          "cache" true
          "exchange" (vs/jm
            "active" false
            "method" "POST"
            "path" "auth/token"
            "refresh" ""
            "request" "refresh_token"
            "response" "access_token"
            "retries" 1
            "statuses" (vs/jt
              401))
          "name" "univec"
          "providers" (vs/jt
            (vs/jm
              "kind" "boru"
              "namespace" "sdk")))
        "optspec" (vs/jm)
        "strict" false
        "transport" "wrap")
      "streaming" (vs/jm
        "options" (vs/jm
          "active" false
          "chunkDelay" 0
          "chunkSize" 0)
        "optspec" (vs/jm
          "ops" "`$LIST`"
          "sleep" "`$FUNCTION`")
        "strict" false
        "transport" "none")
      "telemetry" (vs/jm
        "options" (vs/jm
          "active" false)
        "optspec" (vs/jm
          "exporter" "`$FUNCTION`"
          "headers" "`$MAP`"
          "idgen" "`$FUNCTION`"
          "now" "`$FUNCTION`")
        "strict" false
        "transport" "none")
      "test" (vs/jm
        "options" (vs/jm
          "active" false)
        "optspec" (vs/jm
          "entity" "`$MAP`"
          "net" "`$MAP`")
        "strict" false
        "transport" "base")
      "timeout" (vs/jm
        "options" (vs/jm
          "active" false
          "ms" 30000)
        "optspec" (vs/jm
          "clearTimer" "`$FUNCTION`"
          "setTimer" "`$FUNCTION`")
        "strict" false
        "transport" "wrap"))
    "main" (vs/jm
      "name" "Univec"
      "slug" "univec"
      "target" "clojure"
      "version" "0.1.2")
    "options" (vs/jm
      "auth" (vs/jm
        "prefix" "Bearer")
      "base" "https://api.univec.ai"
      "entity" (vs/jm
        "convert" (vs/jm)
        "embed" (vs/jm)
        "ephemeral_key" (vs/jm)
        "model" (vs/jm))
      "headers" (vs/jm
        "content-type" "application/json"))))

(def feature-plugins
  {"secrets" [p-boru/boru p-hashicorp/hashicorp]})

(def feature-extra
  {"secrets" (fn [] (sdk.feature.secrets/secrets-feature (get feature-plugins "secrets")))})
